import { strict as assert } from 'node:assert';
import { after, before, test } from 'node:test';

import pg from 'pg';

import { DATABASE_ROLE_CAPABILITIES_QUERY } from './database-role-capabilities.mjs';
import {
  probeExists,
  probeIndicatesDrift,
} from './migration-catalog-probes.mjs';
import { assertReadOnlyCapabilities } from './verify-db-read-only-lib.mjs';
import { assertWorkerDatabaseCapabilities } from './verify-worker-db-role-lib.mjs';

const { Client } = pg;
const databaseUrl = process.env.WI1628_ADMIN_DATABASE_URL;
const roleNames = {
  readOnly: 'wi1628_guard_readonly',
  app: 'wi1628_guard_app',
  roleAdmin: 'wi1628_guard_role_admin',
  bypass: 'wi1628_guard_bypass',
  owner: 'wi1628_guard_owner',
  setRoleLogin: 'wi1628_guard_set_role_login',
  setRoleAdmin: 'wi1628_guard_set_role_admin',
  adminOptionLogin: 'wi1628_guard_admin_option_login',
  adminOptionTarget: 'wi1628_guard_admin_option_target',
};
let client;

async function capabilitiesFor(roleName) {
  await client.query(`SET ROLE "${roleName}"`);
  try {
    const result = await client.query(DATABASE_ROLE_CAPABILITIES_QUERY);
    return result.rows[0];
  } finally {
    await client.query('RESET ROLE');
  }
}

before(async () => {
  if (!databaseUrl) return;
  client = new Client({ connectionString: databaseUrl });
  await client.connect();
  await client.query('DROP SCHEMA IF EXISTS wi1628_guard CASCADE');
  for (const roleName of Object.values(roleNames)) {
    await client.query(`DROP ROLE IF EXISTS "${roleName}"`);
  }
  await client.query('REVOKE CREATE ON SCHEMA public FROM PUBLIC');
  await client.query(`CREATE ROLE "${roleNames.readOnly}" NOLOGIN`);
  await client.query(`CREATE ROLE "${roleNames.app}" NOLOGIN`);
  await client.query(`CREATE ROLE "${roleNames.roleAdmin}" NOLOGIN CREATEROLE`);
  await client.query(`CREATE ROLE "${roleNames.bypass}" NOLOGIN BYPASSRLS`);
  await client.query(`CREATE ROLE "${roleNames.owner}" NOLOGIN`);
  await client.query(
    `CREATE ROLE "${roleNames.setRoleLogin}" NOLOGIN NOINHERIT`,
  );
  await client.query(
    `CREATE ROLE "${roleNames.setRoleAdmin}" NOLOGIN CREATEROLE`,
  );
  await client.query(
    `GRANT "${roleNames.setRoleAdmin}" TO "${roleNames.setRoleLogin}"`,
  );
  await client.query(
    `CREATE ROLE "${roleNames.adminOptionLogin}" NOLOGIN NOINHERIT`,
  );
  await client.query(
    `CREATE ROLE "${roleNames.adminOptionTarget}" NOLOGIN CREATEROLE`,
  );
  await client.query(
    `GRANT "${roleNames.adminOptionTarget}" TO "${roleNames.adminOptionLogin}" WITH ADMIN TRUE, SET FALSE, INHERIT FALSE`,
  );
  await client.query('CREATE SCHEMA wi1628_guard');
  await client.query(`
    CREATE TABLE wi1628_guard.records (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      value text NOT NULL
    )
  `);
  await client.query(
    `GRANT USAGE ON SCHEMA wi1628_guard TO ${Object.values(roleNames)
      .map((roleName) => `"${roleName}"`)
      .join(', ')}`,
  );
  await client.query(
    `GRANT SELECT ON wi1628_guard.records TO "${roleNames.readOnly}"`,
  );
  await client.query(
    `GRANT SELECT, INSERT, UPDATE, DELETE ON wi1628_guard.records TO "${roleNames.app}"`,
  );
  await client.query(
    `GRANT USAGE, UPDATE ON SEQUENCE wi1628_guard.records_id_seq TO "${roleNames.app}"`,
  );
  await client.query(`CREATE TABLE wi1628_guard.owned_record (id integer)`);
  await client.query(
    `ALTER TABLE wi1628_guard.owned_record OWNER TO "${roleNames.owner}"`,
  );
  await client.query(
    `GRANT SELECT, INSERT, UPDATE, DELETE ON wi1628_guard.owned_record TO "${roleNames.app}"`,
  );
});

after(async () => {
  if (!client) return;
  await client.query('RESET ROLE');
  await client.query('DROP SCHEMA IF EXISTS wi1628_guard CASCADE');
  for (const roleName of Object.values(roleNames)) {
    await client.query(`DROP ROLE IF EXISTS "${roleName}"`);
  }
  await client.end();
});

test(
  'catalog query accepts SELECT-only and rejects every write/admin capability',
  { skip: !databaseUrl },
  async () => {
    const readOnly = await capabilitiesFor(roleNames.readOnly);
    assert.doesNotThrow(() => assertReadOnlyCapabilities(readOnly));

    const app = await capabilitiesFor(roleNames.app);
    assert.throws(() => assertReadOnlyCapabilities(app), /table write/i);
    assert.doesNotThrow(() =>
      assertWorkerDatabaseCapabilities(app, { expectedBypassRls: false }),
    );

    const roleAdmin = await capabilitiesFor(roleNames.roleAdmin);
    assert.throws(() => assertReadOnlyCapabilities(roleAdmin), /role create/i);
    assert.throws(
      () =>
        assertWorkerDatabaseCapabilities(roleAdmin, {
          expectedBypassRls: false,
        }),
      /role create/i,
    );

    const bypass = await capabilitiesFor(roleNames.bypass);
    assert.throws(
      () => assertReadOnlyCapabilities(bypass),
      /row-level security/i,
    );
    assert.throws(
      () =>
        assertWorkerDatabaseCapabilities(bypass, {
          expectedBypassRls: false,
        }),
      /BYPASSRLS posture/i,
    );

    const owner = await capabilitiesFor(roleNames.owner);
    assert.throws(
      () => assertReadOnlyCapabilities(owner),
      /owns application objects/i,
    );
    assert.throws(
      () =>
        assertWorkerDatabaseCapabilities(owner, {
          expectedBypassRls: false,
        }),
      /owns application objects/i,
    );

    const setRoleLogin = await capabilitiesFor(roleNames.setRoleLogin);
    assert.throws(() => assertReadOnlyCapabilities(setRoleLogin), /SET ROLE/i);
    assert.throws(
      () =>
        assertWorkerDatabaseCapabilities(setRoleLogin, {
          expectedBypassRls: false,
        }),
      /SET ROLE/i,
    );

    const adminOptionLogin = await capabilitiesFor(roleNames.adminOptionLogin);
    assert.equal(adminOptionLogin.has_forbidden_set_role_path, false);
    assert.equal(adminOptionLogin.has_role_admin_path, true);
    assert.throws(
      () => assertReadOnlyCapabilities(adminOptionLogin),
      /role ADMIN/i,
    );
    assert.throws(
      () =>
        assertWorkerDatabaseCapabilities(adminOptionLogin, {
          expectedBypassRls: false,
        }),
      /role ADMIN/i,
    );
  },
);

test(
  'ADMIN TRUE with SET FALSE can self-enable the forbidden SET ROLE path',
  { skip: !databaseUrl },
  async () => {
    await client.query(
      `SET SESSION AUTHORIZATION "${roleNames.adminOptionLogin}"`,
    );
    try {
      await assert.rejects(
        client.query(`SET ROLE "${roleNames.adminOptionTarget}"`),
        /permission denied/i,
      );
      await client.query(
        `GRANT "${roleNames.adminOptionTarget}" TO "${roleNames.adminOptionLogin}" WITH SET TRUE`,
      );
      await client.query(`SET ROLE "${roleNames.adminOptionTarget}"`);
      const result = await client.query(
        'SELECT rolcreaterole FROM pg_roles WHERE rolname = current_user',
      );
      assert.equal(result.rows[0]?.rolcreaterole, true);
    } finally {
      await client.query('RESET ROLE');
      await client.query('RESET SESSION AUTHORIZATION');
    }
  },
);

test(
  'catalog probes distinguish clean pending DDL from out-of-band additive and drop drift',
  { skip: !databaseUrl },
  async () => {
    const query = async (text, params) =>
      (await client.query(text, params)).rows;
    await client.query(
      'CREATE INDEX records_value_idx ON wi1628_guard.records (value)',
    );
    await client.query(
      'ALTER TABLE wi1628_guard.records ADD CONSTRAINT records_value_check CHECK (length(value) > 0)',
    );
    await client.query(
      `CREATE TYPE wi1628_guard.record_state AS ENUM ('open', 'closed')`,
    );
    await client.query(
      'ALTER TABLE wi1628_guard.records ENABLE ROW LEVEL SECURITY',
    );
    await client.query(
      'CREATE POLICY records_policy ON wi1628_guard.records USING (true)',
    );

    const existingProbes = [
      { kind: 'relation', schema: 'wi1628_guard', name: 'records' },
      { kind: 'relation', schema: 'wi1628_guard', name: 'records_value_idx' },
      {
        kind: 'column',
        schema: 'wi1628_guard',
        table: 'records',
        name: 'value',
      },
      {
        kind: 'constraint',
        schema: 'wi1628_guard',
        table: 'records',
        name: 'records_value_check',
      },
      { kind: 'type', schema: 'wi1628_guard', name: 'record_state' },
      {
        kind: 'enum-value',
        schema: 'wi1628_guard',
        type: 'record_state',
        value: 'closed',
      },
      {
        kind: 'policy',
        schema: 'wi1628_guard',
        table: 'records',
        name: 'records_policy',
      },
      {
        kind: 'column-nullability',
        schema: 'wi1628_guard',
        table: 'records',
        name: 'value',
        notNull: true,
      },
      {
        kind: 'row-level-security',
        schema: 'wi1628_guard',
        table: 'records',
        enabled: true,
      },
      { kind: 'extension', name: 'plpgsql' },
    ];

    for (const probe of existingProbes) {
      assert.equal(await probeExists(query, probe), true, probe.kind);
      assert.equal(
        probeIndicatesDrift(probe, true),
        true,
        `an existing unjournaled ${probe.kind} must be additive drift`,
      );
    }

    const absentProbe = {
      kind: 'relation',
      schema: 'wi1628_guard',
      name: 'not_created',
    };
    assert.equal(await probeExists(query, absentProbe), false);
    assert.equal(probeIndicatesDrift(absentProbe, false), false);

    const pendingDropProbe = {
      kind: 'relation',
      schema: 'wi1628_guard',
      name: 'records_value_idx',
      expectedExists: true,
    };
    assert.equal(probeIndicatesDrift(pendingDropProbe, true), false);
    await client.query('DROP INDEX wi1628_guard.records_value_idx');
    const existsAfterOutOfBandDrop = await probeExists(query, pendingDropProbe);
    assert.equal(existsAfterOutOfBandDrop, false);
    assert.equal(probeIndicatesDrift(pendingDropProbe, false), true);
  },
);
