// ---------------------------------------------------------------------------
// [WI-2628] Protected-lexeme corpus for the shared multilingual persisted-
// learning-text safety gate (MMT-ADR-0036 §4.6, Alternative 10 rejected the
// English-regex-at-each-caller design this replaces).
//
// SCOPE DISCIPLINE — the corpus names *conditions*, and the grammar around it
// names *attribution*. Mere mention of a condition is NOT a block: the gate
// blocks person-attributed clinical text. `apps/api/eval-llm/fixtures/probes/
// battery.ts` line ~999 deliberately contains "ADHD-style short-burst
// support" — legitimate personalization language that must never be a block.
//
// CONFIDENCE IS RECORDED IN THE DATA, NOT ONLY IN A REPORT. `confidence` is
// 'reviewed' only for the English set, which is a direct port of the shipped,
// Art-9-decision-scoped list in persisted-learning-text-guard.ts. Every other
// language is 'model-generated' and REQUIRES native-speaker review before it
// can be relied on as a compliance control. Under-claim, never over-claim.
//
// Every entry is a LITERAL phrase (regex metacharacters are escaped by the
// scanner; internal spaces become flexible whitespace). Inflected forms are
// listed explicitly rather than approximated by a bare stem — a bare stem both
// over-fires (matching unrelated words) and under-fires (missing case endings).
//
// ---------------------------------------------------------------------------
// [WI-3142] THE REMAINING ARTICLE 9 DOMAINS — SCOPE POLICY
//
// The corpus originally carried health/disability only. Racial/ethnic origin,
// political opinions, religious & philosophical beliefs, trade-union membership,
// sex life/sexual orientation and (narrowly) genetic data were added to close
// Gap 1 of the memory-unlock evidence package
// (docs/compliance/memory-unlock-package/a5-art9-suppression.md).
//
// THE DEFAULT FOR THOSE DOMAINS IS `unnamed-attribution-only`, NOT `broad`, and
// that is a ruling rather than a convenience. "Catholic", "communist", "gay",
// "Roma", "union member" are ordinary words in history, civics and
// religious-education homework. In the broad scope a bare mention alone makes
// text non-clear, so every schoolwork note on the Reformation or the Industrial
// Revolution would route to the judge. Broad is reserved for terms that are
// near-exclusively disclosure-shaped; on review NONE of the new-domain
// candidates qualified, so the broad sets are unchanged by this extension.
//
// WHY A THIRD SCOPE RATHER THAN REUSING `attributed-only`. That scope's grammar
// includes the Latin "capitalized token = person name" heuristic that makes
// `Petr has dyslexia.` block. Over a religion or politics slot the same
// heuristic hard-blocks the commonest shape in history homework —
// `Martin Luther was Catholic.`, `Gandhi was Hindu.` — with no judge appeal.
// The Article 9 risk this gate exists for is a characterisation of the LEARNER
// (the position document's discussion-vs-characterisation distinction), so the
// new scope keeps every attribution shape that names a data subject and drops
// the bare-name heuristic alone.
//
// TERMS DELIBERATELY EXCLUDED, because their attributed form is ordinary prose
// far more often than a disclosure: bare colour and continent adjectives
// ("black", "white", "asian", "african" — "my black cat", "their Asian
// elephant"); "conservative"/"liberal" ("a conservative estimate");
// "orthodox" ("his orthodox method"); "straight" ("a straight line");
// "asexual" ("their asexual reproduction" is core biology); bare "union"
// (the European Union, a union of sets); "coming out" ("he is coming out of
// the room"); "boyfriend"/"girlfriend"/"virgin". Where a domain still needed
// the concept, a multi-word disclosure-shaped form carries it instead
// ("politically conservative", "orthodox jewish", "union member").
//
// BIOMETRIC DATA IS NOT REPRESENTED, and that is a judgment, not an omission.
// Article 9 covers biometric data processed *for the purpose of uniquely
// identifying a person*; the category is defined by the processing, not by any
// vocabulary a learner would type. Terms like "fingerprint" or "facial
// recognition" are computing-curriculum topics whose attributed forms are not
// disclosures. Genetic data is included only through multi-word forms that are
// inherently disclosure-shaped ("DNA test result", "genetic screening").
// ---------------------------------------------------------------------------

import type { ConversationLanguage } from '@eduagent/schemas';

export type CorpusConfidence = 'reviewed' | 'model-generated';

/**
 * How a condition term may be detected — the explicit lexeme-scope contract the
 * Stage-3 reachability ruling requires (2026-07-26).
 *
 * `broad` — detectable on its own, in ANY of the ten languages' prose. A bare
 * mention is enough to make the text non-clear (ambiguous, then judged).
 *
 * `attributed-only` — detectable ONLY inside an attribution construction, and
 * ONLY through the grammar of the language that declares it. These are terms
 * that are homographs of ordinary words in another supported language: Spanish
 * `TEA`, German `ADS`, Norwegian `ADD` collide with English "tea", "ads",
 * "add". They were previously OMITTED from the corpus outright, which made
 * `El alumno tiene TEA` classify `clear` and — because the gate reaches
 * attribution analysis only after a protected-lexeme match — unreachable by any
 * judge-side change. Putting them in this scope makes the attributed use
 * deterministically `block` while leaving the bare mention outside the
 * cross-language detector entirely, so "tea the drink" never fires.
 *
 * `unnamed-attribution-only` — [WI-3142] detectable ONLY inside an attribution
 * construction whose subject NAMES A DATA SUBJECT: a person reference
 * (`the learner`, `she`, `I`), a possessive determiner (`her`, `the student's`),
 * or — for Japanese — the topic/possessive particles and honorific suffixes.
 * Everything `attributed-only` does, MINUS the bare "capitalized token = person
 * name" heuristic. This is the default scope for the Article 9 domains beyond
 * health (see the scope-policy block in this file's header): over a religion or
 * politics slot the name heuristic blocks `Martin Luther was Catholic.` — a
 * statement about a historical figure, not a characterisation of the learner —
 * and does so deterministically, with no judge appeal.
 *
 * The scanner assigns each scope to a detection policy through an EXHAUSTIVE
 * switch, so adding a scope is a compile error rather than a silent no-op.
 * See `scan.ts` → `detectionPolicyFor`.
 */
export type LexemeScope =
  | 'broad'
  | 'attributed-only'
  | 'unnamed-attribution-only';

export interface LanguageCorpus {
  readonly language: ConversationLanguage;
  /** 'reviewed' = expert-validated. 'model-generated' = needs native review. */
  readonly confidence: CorpusConfidence;
  /**
   * Protected Article 9 terms, partitioned by detection scope. Contribute the
   * "protected lexeme present" signal — `broad` on its own, the two attribution
   * scopes only within this language's attribution grammar. ALL keys are
   * REQUIRED, so a newly added language cannot silently omit a scope decision.
   */
  readonly lexemes: Readonly<Record<LexemeScope, readonly string[]>>;
  /** Generic person references (pronouns, learner roles) usable as an attribution subject. */
  readonly personReferences: readonly string[];
  /** Possessive determiners: "<det> <lexeme>" is attribution without a verb. */
  readonly possessiveDeterminers: readonly string[];
  /** Attribution verbs / phrases linking a person to a lexeme. */
  readonly attributionPhrases: readonly string[];
  /** Hedges that make an attribution an *inference* rather than an assertion. */
  readonly inferenceMarkers: readonly string[];
  /** Articles/quantifiers tolerated between the verb and the lexeme. */
  readonly determiners: readonly string[];
  /**
   * Whether the script has letter case. When false the "capitalized token =
   * person name" heuristic used for Latin scripts is meaningless and MUST NOT
   * be applied — see `rawAttributionPatterns`.
   */
  readonly scriptHasCase: boolean;
  /**
   * Raw regex sources (NOT escaped) for scripts without case or word
   * boundaries. `LEX` is substituted with the full lexeme alternation.
   */
  readonly rawAttributionPatterns?: readonly string[];
}

const EN: LanguageCorpus = {
  language: 'en',
  // Direct port of the shipped WI-1195 Art-9 list — the only expert-scoped set.
  confidence: 'reviewed',
  lexemes: {
    broad: [
      'adhd',
      'autism',
      'autistic',
      'dyslexia',
      'dyslexic',
      'dyscalculia',
      'dyscalculic',
      'learning disability',
      'learning disabilities',
      // Hyphenated compounds, matching how 'mental-health condition' is already
      // carried. Without these, "a learning-disability diagnosis" scanned clear
      // while the space-separated form blocked.
      'learning-disability',
      'learning-disabilities',
      'mental health condition',
      'mental-health condition',
      'physical health condition',
      'physical-health condition',
    ],
    'attributed-only': [],
    // [WI-3142] The remaining Article 9 domains, authored (not generated) and
    // therefore covered by this corpus's 'reviewed' confidence. Plural and
    // hyphenated variants are listed explicitly — the header's no-bare-stem rule
    // applies here too.
    'unnamed-attribution-only': [
      // --- racial or ethnic origin -------------------------------------------
      'roma',
      'romani',
      'romany',
      'sinti',
      'dalit',
      'indigenous',
      'aboriginal',
      'inuit',
      'sami',
      'sámi',
      'maori',
      'māori',
      'kurd',
      'kurds',
      'kurdish',
      'latino',
      'latina',
      'latinx',
      'hispanic',
      'african american',
      'african-american',
      'afro-caribbean',
      'mixed race',
      'mixed-race',
      'biracial',
      'multiracial',
      'ethnicity',
      'ethnic origin',
      'ethnic background',
      'ethnic minority',
      'ethnic minorities',
      'person of colour',
      'person of color',
      'people of colour',
      'people of color',
      'immigrant background',
      'migrant background',
      'refugee background',
      // --- political opinions ------------------------------------------------
      'communist',
      'communists',
      'marxist',
      'marxists',
      'leninist',
      'maoist',
      'trotskyist',
      'socialist',
      'socialists',
      'anarchist',
      'anarchists',
      'fascist',
      'fascists',
      'neo-nazi',
      'neo-nazis',
      'white supremacist',
      'nationalist',
      'nationalists',
      'separatist',
      'far-right',
      'far right',
      'far-left',
      'far left',
      'left-wing',
      'left wing',
      'right-wing',
      'right wing',
      'republican',
      'republicans',
      'democrat',
      'democrats',
      'feminist',
      'feminists',
      'activist',
      'activists',
      'eurosceptic',
      'pro-life',
      'pro-choice',
      'politically active',
      'politically conservative',
      'politically liberal',
      'political opinion',
      'political opinions',
      'political views',
      'political affiliation',
      'political party',
      // --- religious or philosophical beliefs --------------------------------
      'catholic',
      'catholics',
      'protestant',
      'protestants',
      'christian',
      'christians',
      'muslim',
      'muslims',
      'jew',
      'jews',
      'jewish',
      'hindu',
      'hindus',
      'buddhist',
      'buddhists',
      'sikh',
      'sikhs',
      'jain',
      'taoist',
      'shinto',
      'atheist',
      'atheists',
      'agnostic',
      'agnostics',
      'humanist',
      'humanists',
      'evangelical',
      'baptist',
      'methodist',
      'lutheran',
      'presbyterian',
      'anglican',
      'mormon',
      "jehovah's witness",
      'jehovahs witness',
      'orthodox christian',
      'orthodox jew',
      'orthodox jewish',
      'pagan',
      'wiccan',
      'rastafarian',
      'zoroastrian',
      'devout',
      'practising catholic',
      'practicing catholic',
      'practising muslim',
      'practicing muslim',
      'converted to islam',
      'converted to christianity',
      'converted to judaism',
      'religious belief',
      'religious beliefs',
      'religious faith',
      'faith background',
      'hijab',
      'niqab',
      'kippah',
      'yarmulke',
      // --- trade-union membership --------------------------------------------
      'union member',
      'union members',
      'union membership',
      'union card',
      'union dues',
      'union rep',
      'union representative',
      'union official',
      'trade union member',
      'trade union members',
      'trade unionist',
      'trade unionists',
      'unionised',
      'unionized',
      'shop steward',
      'member of a union',
      'member of the union',
      'joined a union',
      'joined the union',
      // --- sex life or sexual orientation ------------------------------------
      'gay',
      'lesbian',
      'lesbians',
      'bisexual',
      'bisexuals',
      'pansexual',
      'queer',
      'homosexual',
      'homosexuals',
      'heterosexual',
      'lgbt',
      'lgbt+',
      'lgbtq',
      'lgbtq+',
      'lgbtqia',
      'transgender',
      'non-binary',
      'nonbinary',
      'intersex',
      'sexual orientation',
      'sexually active',
      'sex life',
      // --- genetic data (multi-word, disclosure-shaped forms only) -----------
      'dna test',
      'dna tests',
      'dna test result',
      'dna test results',
      'genetic test',
      'genetic tests',
      'genetic test result',
      'genetic test results',
      'genetic testing',
      'genetic screening',
      'genetic condition',
      'genetic disorder',
      'hereditary condition',
      'hereditary disease',
    ],
  },
  personReferences: [
    'i',
    'you',
    'learner',
    'student',
    'child',
    'user',
    'profile',
    'they',
    'he',
    'she',
  ],
  possessiveDeterminers: [
    'learner',
    'student',
    'child',
    'user',
    'profile',
    'their',
    'his',
    'her',
    'your',
    'my',
  ],
  attributionPhrases: [
    'may have',
    'might have',
    'could have',
    'likely has',
    'appears to have',
    'seems to have',
    'shows signs of',
    'is diagnosed with',
    'was diagnosed with',
    'were diagnosed with',
    'has',
    'have',
    'had',
    'is',
    'am',
    'are',
    'was',
    'were',
  ],
  inferenceMarkers: [
    'may',
    'might',
    'could',
    'likely',
    'probably',
    'possibly',
    'suspected',
    'appears',
    'seems',
    'signs of',
  ],
  determiners: ['a', 'an', 'the'],
  scriptHasCase: true,
};

const CS: LanguageCorpus = {
  language: 'cs',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'adhd',
      // Czech declines: nominative/genitive/dative/instrumental forms listed.
      'autismus',
      'autismu',
      'autismem',
      'autista',
      'autisty',
      'autistou',
      'autistický',
      'autistická',
      'autistické',
      'autistického',
      'autistickou',
      'dyslexie',
      'dyslexii',
      'dyslexií',
      'dyslektik',
      'dyslektika',
      'dyslektický',
      'dyslektická',
      'dyskalkulie',
      'dyskalkulii',
      'dyskalkulií',
      'dyskalkulik',
      'porucha učení',
      'poruchu učení',
      'poruchou učení',
      'poruchy učení',
      'specifická porucha učení',
      'duševní onemocnění',
      'duševní porucha',
      'duševní poruchu',
      'psychické onemocnění',
      'tělesné postižení',
      'tělesným postižením',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'rom',
      'roma',
      'romovi',
      'romem',
      'romka',
      'romky',
      'romce',
      'romku',
      'romkou',
      'přistěhovalec',
      'přistěhovalce',
      'přistěhovalci',
      'přistěhovalcem',
      'přistěhovalkyně',
      'přistěhovalkyni',
      'přistěhovalkyní',
      'domorodec',
      'domorodce',
      'domorodci',
      'domorodcem',
      'domorodkyně',
      'domorodkyni',
      'domorodkyní',
      'etnická menšina',
      'etnické menšiny',
      'etnické menšině',
      'etnickou menšinu',
      'etnickou menšinou',
      'smíšeného původu',
      'imigrantského původu',
      'etnický původ',
      'etnického původu',
      'etnickému původu',
      'etnickým původem',
      // --- political opinions or affiliation ---
      'komunista',
      'komunisty',
      'komunistu',
      'komunistovi',
      'komunistou',
      'komunistka',
      'komunistky',
      'komunistku',
      'komunistce',
      'komunistkou',
      'socialista',
      'socialisty',
      'socialistu',
      'socialistovi',
      'socialistou',
      'socialistka',
      'socialistky',
      'socialistku',
      'socialistce',
      'socialistkou',
      'feministka',
      'feministky',
      'feministku',
      'feministce',
      'feministkou',
      'člen strany',
      'člena strany',
      'členu strany',
      'členem strany',
      'členka strany',
      'členky strany',
      'členku strany',
      'člence strany',
      'členkou strany',
      'politických názorů',
      'politickými názory',
      'politického přesvědčení',
      'politickým přesvědčením',
      // --- religious or philosophical beliefs ---
      'katolík',
      'katolíka',
      'katolíkovi',
      'katolíkem',
      'katolička',
      'katoličky',
      'katoličku',
      'katoličce',
      'katoličkou',
      'muslim',
      'muslima',
      'muslimovi',
      'muslimem',
      'muslimka',
      'muslimky',
      'muslimku',
      'muslimce',
      'muslimkou',
      'ateista',
      'ateisty',
      'ateistovi',
      'ateistou',
      'ateistka',
      'ateistky',
      'ateistku',
      'ateistce',
      'ateistkou',
      'křesťan',
      'křesťana',
      'křesťanovi',
      'křesťanem',
      'křesťanka',
      'křesťanky',
      'křesťanku',
      'křesťance',
      'křesťankou',
      'náboženské přesvědčení',
      'náboženského přesvědčení',
      'náboženskému přesvědčení',
      'náboženským přesvědčením',
      'hidžáb',
      'konvertoval k islámu',
      'konvertovala k islámu',
      'zbožný',
      'zbožná',
      // --- trade-union membership ---
      'odborář',
      'odboráře',
      'odboráři',
      'odborářem',
      'odborářka',
      'odborářky',
      'odborářku',
      'odborářce',
      'odborářkou',
      'člen odborů',
      'člena odborů',
      'členu odborů',
      'členem odborů',
      'členka odborů',
      'členky odborů',
      'členku odborů',
      'člence odborů',
      'členkou odborů',
      'odborový funkcionář',
      'odborového funkcionáře',
      'odborovému funkcionáři',
      'odborovým funkcionářem',
      'odborová funkcionářka',
      'odborové funkcionářky',
      'odborovou funkcionářku',
      'odborové funkcionářce',
      'odborovou funkcionářkou',
      'odborové příspěvky',
      'v odborech',
      'organizován v odborech',
      'organizována v odborech',
      // --- sex life or sexual orientation ---
      'gay',
      'gaye',
      'gayovi',
      'gayem',
      'lesbička',
      'lesbičky',
      'lesbičku',
      'lesbičce',
      'lesbičkou',
      'bisexuál',
      'bisexuála',
      'bisexuálovi',
      'bisexuálem',
      'bisexuálka',
      'bisexuálky',
      'bisexuálku',
      'bisexuálce',
      'bisexuálkou',
      'homosexuál',
      'homosexuála',
      'homosexuálovi',
      'homosexuálem',
      'homosexuálka',
      'homosexuálky',
      'homosexuálku',
      'homosexuálce',
      'homosexuálkou',
      'heterosexuál',
      'heterosexuála',
      'heterosexuálovi',
      'heterosexuálem',
      'heterosexuálka',
      'heterosexuálky',
      'heterosexuálku',
      'heterosexuálce',
      'heterosexuálkou',
      'queer',
      'lgbt',
      'lgbtq',
      'transgender',
      'intersex',
      'sexuální orientace',
      'sexuální orientaci',
      'sexuální orientací',
      'sexuálně aktivní',
      // --- genetic data ---
      'genetický test',
      'genetického testu',
      'genetickému testu',
      'genetickým testem',
      'genetické vyšetření',
      'genetickému vyšetření',
      'genetickým vyšetřením',
      'dědičná choroba',
      'dědičné choroby',
      'dědičné chorobě',
      'dědičnou chorobu',
      'dědičnou chorobou',
      'dědičná porucha',
      'dědičné poruchy',
      'dědičné poruše',
      'dědičnou poruchu',
      'dědičnou poruchou',
      'genetická predispozice',
      'genetické predispozice',
      'genetické predispozici',
      'genetickou predispozici',
      'genetickou predispozicí',
      'analýza dna',
      'analýzy dna',
      'analýze dna',
      'analýzu dna',
      'analýzou dna',
      'výsledek testu dna',
      'výsledku testu dna',
      'výsledkem testu dna',
    ],
  },
  personReferences: [
    'já',
    'ty',
    'on',
    'ona',
    'oni',
    'žák',
    'žákyně',
    'student',
    'studentka',
    'dítě',
    'uživatel',
    'profil',
  ],
  possessiveDeterminers: [
    'jeho',
    'její',
    'jejich',
    'můj',
    'moje',
    'tvůj',
    'tvoje',
    'žákova',
    'žákovo',
    'studentova',
    'dítěte',
    'uživatele',
  ],
  attributionPhrases: [
    'má',
    'mám',
    'máš',
    'mají',
    'měl',
    'měla',
    'je',
    'jsem',
    'jsi',
    'jsou',
    'byl',
    'byla',
    'byl diagnostikován',
    'byla diagnostikována',
    'má diagnózu',
    'jeví známky',
    'pravděpodobně má',
    'možná má',
  ],
  inferenceMarkers: [
    'pravděpodobně',
    'možná',
    'asi',
    'zdá se',
    'jeví známky',
    'podezření',
    'suspektní',
  ],
  determiners: [],
  scriptHasCase: true,
};

const ES: LanguageCorpus = {
  language: 'es',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'tdah',
      'adhd',
      'autismo',
      'autista',
      'trastorno del espectro autista',
      // NOTE: the Spanish acronym "TEA" is NOT here — it is the English word
      // "tea", and broad lexeme detection runs across all ten languages. It lives
      // in this corpus's 'attributed-only' scope instead, so `El alumno tiene TEA`
      // blocks while an English "a cup of tea" never fires.
      'dislexia',
      'disléxico',
      'disléxica',
      'discalculia',
      'trastorno de aprendizaje',
      'trastornos de aprendizaje',
      'dificultad de aprendizaje',
      'dificultades de aprendizaje',
      'discapacidad de aprendizaje',
      'trastorno de salud mental',
      'enfermedad mental',
      'discapacidad física',
    ],
    'attributed-only': ['tea'],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'gitano',
      'gitana',
      'gitanos',
      'gitanas',
      'kurdo',
      'kurda',
      'kurdos',
      'kurdas',
      'indígena',
      'indígenas',
      'mestizo',
      'mestiza',
      'mestizos',
      'mestizas',
      'mulato',
      'mulata',
      'mulatos',
      'mulatas',
      'payo',
      'paya',
      'payos',
      'payas',
      'de origen mixto',
      'de herencia mixta',
      'de origen inmigrante',
      'minoría étnica',
      'etnia',
      // --- political opinions or affiliation ---
      'comunista',
      'comunistas',
      'socialista',
      'socialistas',
      'anarquista',
      'anarquistas',
      'nacionalista',
      'nacionalistas',
      'fascista',
      'fascistas',
      'feminista',
      'feministas',
      'militante',
      'militantes',
      'activista',
      'activistas',
      'republicano',
      'republicana',
      'republicanos',
      'republicanas',
      'monárquico',
      'monárquica',
      'monárquicos',
      'monárquicas',
      'afiliado al partido',
      'afiliada al partido',
      'afiliados al partido',
      'afiliadas al partido',
      'miembro del partido',
      'miembros del partido',
      'de extrema derecha',
      'de extrema izquierda',
      'opiniones políticas',
      'ideología política',
      // --- religious or philosophical beliefs ---
      'católico',
      'católica',
      'católicos',
      'católicas',
      'protestante',
      'protestantes',
      'musulmán',
      'musulmana',
      'musulmanes',
      'musulmanas',
      'judío',
      'judía',
      'judíos',
      'judías',
      'hindú',
      'hindúes',
      'budista',
      'budistas',
      'ateo',
      'atea',
      'ateos',
      'ateas',
      'agnóstico',
      'agnóstica',
      'agnósticos',
      'agnósticas',
      'evangélico',
      'evangélica',
      'evangélicos',
      'evangélicas',
      'testigo de jehová',
      'testigos de jehová',
      'suní',
      'suníes',
      'chií',
      'chiíes',
      'mormón',
      'mormona',
      'mormones',
      'mormonas',
      'hijab',
      'kipá',
      'convertido al islam',
      'convertida al islam',
      // --- trade-union membership ---
      'sindicalista',
      'sindicalistas',
      'afiliado a un sindicato',
      'afiliada a un sindicato',
      'afiliados a un sindicato',
      'afiliadas a un sindicato',
      'miembro de un sindicato',
      'miembros de un sindicato',
      'delegado sindical',
      'delegada sindical',
      'delegados sindicales',
      'delegadas sindicales',
      'cuota sindical',
      'cuotas sindicales',
      'sindicalizado',
      'sindicalizada',
      'sindicalizados',
      'sindicalizadas',
      // --- sex life or sexual orientation ---
      'gay',
      'gays',
      'lesbiana',
      'lesbianas',
      'bisexual',
      'bisexuales',
      'pansexual',
      'pansexuales',
      'homosexual',
      'homosexuales',
      'heterosexual',
      'heterosexuales',
      'queer',
      'transgénero',
      'trans',
      'intersexual',
      'intersexuales',
      'intersex',
      'lgbt',
      'lgbtq',
      'orientación sexual',
      'sexualmente activo',
      'sexualmente activa',
      'sexualmente activos',
      'sexualmente activas',
      'arromántico',
      'arromántica',
      'arrománticos',
      'arrománticas',
      'demisexual',
      'demisexuales',
      // --- genetic data ---
      'análisis genético',
      'análisis genéticos',
      'condición hereditaria',
      'condiciones hereditarias',
      'enfermedad genética',
      'enfermedades genéticas',
      'enfermedad hereditaria',
      'enfermedades hereditarias',
      'mapa genético',
      'mapas genéticos',
      'marcador genético',
      'marcadores genéticos',
      'perfil genético',
      'perfiles genéticos',
      'predisposición genética',
      'predisposiciones genéticas',
      'prueba de adn',
      'pruebas de adn',
      'prueba genética',
      'pruebas genéticas',
      'riesgo genético',
      'riesgos genéticos',
      'trastorno genético',
      'trastornos genéticos',
    ],
  },
  personReferences: [
    'yo',
    'tú',
    'él',
    'ella',
    'ellos',
    'usted',
    'el alumno',
    'la alumna',
    'alumno',
    'alumna',
    'estudiante',
    'niño',
    'niña',
    'usuario',
    'perfil',
  ],
  possessiveDeterminers: [
    'su',
    'sus',
    'mi',
    'mis',
    'tu',
    'tus',
    'del alumno',
    'del estudiante',
    'del niño',
    'del usuario',
  ],
  attributionPhrases: [
    'tiene',
    'tengo',
    'tienes',
    'tienen',
    'tenía',
    'es',
    'soy',
    'eres',
    'son',
    'era',
    'fue diagnosticado con',
    'fue diagnosticada con',
    'ha sido diagnosticado con',
    'presenta signos de',
    'puede tener',
    'podría tener',
    'probablemente tiene',
    'posiblemente tiene',
  ],
  inferenceMarkers: [
    'puede',
    'podría',
    'probablemente',
    'posiblemente',
    'parece',
    'presenta signos',
    'sospecha',
  ],
  determiners: ['un', 'una', 'el', 'la'],
  scriptHasCase: true,
};

const FR: LanguageCorpus = {
  language: 'fr',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'tdah',
      'adhd',
      'autisme',
      'autiste',
      'trouble du spectre autistique',
      'dyslexie',
      'dyslexique',
      'dyscalculie',
      "trouble d'apprentissage",
      "troubles d'apprentissage",
      "difficulté d'apprentissage",
      "difficultés d'apprentissage",
      'trouble de santé mentale',
      'maladie mentale',
      'handicap physique',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'rom',
      'roms',
      'romni',
      'romnies',
      'sinti',
      'sintis',
      'sintie',
      'sinties',
      'kurde',
      'kurdes',
      'autochtone',
      'autochtones',
      'indigène',
      'indigènes',
      'métis',
      'métisse',
      'métisses',
      'gitan',
      'gitane',
      'gitans',
      'gitanes',
      'manouche',
      'manouches',
      "issu de l'immigration",
      "issue de l'immigration",
      "issus de l'immigration",
      "issues de l'immigration",
      "d'origine mixte",
      'de minorité ethnique',
      "d'origine étrangère",
      // --- political opinions or affiliation ---
      'anarchiste',
      'anarchistes',
      'communiste',
      'communistes',
      'démocrate',
      'démocrates',
      'écologiste',
      'écologistes',
      'fasciste',
      'fascistes',
      'féministe',
      'féministes',
      'marxiste',
      'marxistes',
      'militant',
      'militante',
      'militants',
      'militantes',
      'nationaliste',
      'nationalistes',
      'républicain',
      'républicaine',
      'républicains',
      'républicaines',
      'royaliste',
      'royalistes',
      'socialiste',
      'socialistes',
      "d'extrême droite",
      "d'extrême gauche",
      'membre du parti',
      'opinions politiques',
      'convictions politiques',
      'appartenance politique',
      // --- religious or philosophical beliefs ---
      'athée',
      'athées',
      'agnostique',
      'agnostiques',
      'bouddhiste',
      'bouddhistes',
      'catholique',
      'catholiques',
      "converti à l'islam",
      "convertie à l'islam",
      'de confession juive',
      'de confession musulmane',
      'hindou',
      'hindoue',
      'hindous',
      'hindoues',
      'hijab',
      'juif',
      'juive',
      'juifs',
      'juives',
      'kippa',
      'musulman',
      'musulmane',
      'musulmans',
      'musulmanes',
      'pratiquant',
      'pratiquante',
      'protestant',
      'protestante',
      'protestants',
      'protestantes',
      // --- trade-union membership ---
      'syndicaliste',
      'syndicalistes',
      'syndiqué',
      'syndiquée',
      'syndiqués',
      'syndiquées',
      "membre d'un syndicat",
      "membres d'un syndicat",
      'délégué syndical',
      'déléguée syndicale',
      'délégués syndicaux',
      'déléguées syndicales',
      'cotisation syndicale',
      'cotisations syndicales',
      // --- sex life or sexual orientation ---
      'gay',
      'gays',
      'lesbienne',
      'lesbiennes',
      'lesbien',
      'lesbiens',
      'bisexuel',
      'bisexuelle',
      'bisexuels',
      'bisexuelles',
      'pansexuel',
      'pansexuelle',
      'pansexuels',
      'pansexuelles',
      'queer',
      'homosexuel',
      'homosexuelle',
      'homosexuels',
      'homosexuelles',
      'hétérosexuel',
      'hétérosexuelle',
      'hétérosexuels',
      'hétérosexuelles',
      'lgbt',
      'lgbtq',
      'transgenre',
      'transgenres',
      'intersexe',
      'intersexes',
      'orientation sexuelle',
      'sexuellement actif',
      'sexuellement active',
      'sexuellement actifs',
      'sexuellement actives',
      'hétéro',
      'hétéros',
      'homo',
      'homos',
      'bi',
      // --- genetic data ---
      'analyse génétique',
      'analyses génétiques',
      'carte génétique',
      'cartes génétiques',
      'condition héréditaire',
      'conditions héréditaires',
      'dépistage génétique',
      'dépistages génétiques',
      'donnée génétique',
      'données génétiques',
      'empreinte génétique',
      'empreintes génétiques',
      'maladie héréditaire',
      'maladies héréditaires',
      'marqueur génétique',
      'marqueurs génétiques',
      'origine génétique',
      'origines génétiques',
      'patrimoine génétique',
      'patrimoines génétiques',
      'prédisposition génétique',
      'prédispositions génétiques',
      'profil génétique',
      'profils génétiques',
      'séquençage génétique',
      'séquençages génétiques',
      'test adn',
      'tests adn',
      'test génétique',
      'tests génétiques',
    ],
  },
  personReferences: [
    'je',
    'tu',
    'il',
    'elle',
    'ils',
    'vous',
    "l'élève",
    'élève',
    'étudiant',
    'étudiante',
    'enfant',
    'utilisateur',
    'profil',
  ],
  possessiveDeterminers: [
    'son',
    'sa',
    'ses',
    'mon',
    'ma',
    'mes',
    'ton',
    'ta',
    'tes',
    "de l'élève",
    "de l'enfant",
    "de l'utilisateur",
  ],
  attributionPhrases: [
    'a',
    'ai',
    'as',
    'ont',
    'avait',
    'est',
    'suis',
    'es',
    'sont',
    'était',
    'a été diagnostiqué avec',
    'a été diagnostiquée avec',
    'présente des signes de',
    'peut avoir',
    'pourrait avoir',
    'a probablement',
    'a peut-être',
  ],
  inferenceMarkers: [
    'peut',
    'pourrait',
    'probablement',
    'peut-être',
    'semble',
    'présente des signes',
    'soupçon',
  ],
  determiners: ['un', 'une', 'le', 'la', "l'", 'du', 'de la'],
  scriptHasCase: true,
};

const DE: LanguageCorpus = {
  language: 'de',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'adhs',
      // NOTE: German "ADS" is not broad — homograph of English "ads". It sits in
      // this corpus's 'attributed-only' scope: `Der Schüler hat ADS` blocks, a
      // bare "ads" never fires.
      'adhd',
      'autismus',
      'autistisch',
      'autistische',
      'autistischer',
      'autist',
      'autismus-spektrum-störung',
      'legasthenie',
      'legastheniker',
      'legasthenikerin',
      'dyslexie',
      'dyskalkulie',
      'rechenstörung',
      'lernbehinderung',
      'lernstörung',
      'lernstörungen',
      'psychische erkrankung',
      'psychische störung',
      'körperliche behinderung',
    ],
    'attributed-only': ['ads'],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'migrationshintergrund',
      'migrationshintergrunds',
      'kurde',
      'kurdin',
      'kurdisch',
      'jude',
      'jüdin',
      'jüdisch',
      'romni',
      'jenischer',
      'jenische',
      'jeside',
      'jesidin',
      'jesidisch',
      'alevite',
      'alevitin',
      'alevitisch',
      'indigen',
      'ureinwohner',
      'ureinwohnerin',
      'mischling',
      'halbjude',
      'halbjüdin',
      'ethnie',
      'volksgruppe',
      'ethnische zugehörigkeit',
      'volkszugehörigkeit',
      'gemischter herkunft',
      'ethnischer herkunft',
      // --- political opinions or affiliation ---
      'kommunist',
      'kommunisten',
      'kommunistin',
      'kommunistisch',
      'sozialist',
      'sozialisten',
      'sozialistin',
      'sozialistisch',
      'anarchist',
      'anarchisten',
      'anarchistin',
      'anarchistisch',
      'nationalist',
      'nationalisten',
      'nationalistin',
      'nationalistisch',
      'feminist',
      'feministen',
      'feministin',
      'feministisch',
      'rechtsextrem',
      'rechtsextremist',
      'rechtsextremisten',
      'rechtsextremistin',
      'linksextrem',
      'linksextremist',
      'linksextremisten',
      'linksextremistin',
      'parteimitglied',
      'parteimitglieds',
      'politische ansichten',
      'politischen ansichten',
      'politische einstellung',
      'politischer einstellung',
      'politische überzeugung',
      'politischer überzeugung',
      // --- religious or philosophical beliefs ---
      'katholik',
      'des katholiken',
      'katholikin',
      'der katholikin',
      'katholisch',
      'protestant',
      'des protestanten',
      'protestantin',
      'der protestantin',
      'protestantisch',
      'evangelisch',
      'muslim',
      'des muslims',
      'muslima',
      'der muslima',
      'muslimisch',
      'des juden',
      'der jüdin',
      'hindu',
      'hinduistin',
      'hinduistisch',
      'buddhist',
      'des buddhisten',
      'buddhistin',
      'der buddhistin',
      'buddhistisch',
      'atheist',
      'des atheisten',
      'atheistin',
      'der atheistin',
      'atheistisch',
      'agnostiker',
      'agnostikerin',
      'agnostisch',
      'zum islam konvertiert',
      'religiöse überzeugung',
      'hidschab',
      'kippa',
      // --- trade-union membership ---
      'gewerkschafter',
      'gewerkschafters',
      'gewerkschafterin',
      'gewerkschafterinnen',
      'gewerkschaftler',
      'gewerkschaftlerin',
      'gewerkschaftsmitglied',
      'gewerkschaftsmitglieds',
      'gewerkschaftlich organisiert',
      'in der gewerkschaft',
      'in einer gewerkschaft',
      'mitglied der gewerkschaft',
      'mitglied einer gewerkschaft',
      'mitgliedschaft in der gewerkschaft',
      'gewerkschaftsbeitrag',
      'gewerkschaftsbeiträge',
      'betriebsrat',
      'betriebsrätin',
      'betriebsratsmitglied',
      'vertrauensmann',
      'vertrauensfrau',
      'vertrauensleute',
      // --- sex life or sexual orientation ---
      'bisexuell',
      'bisexueller',
      'bisexuelle',
      'eingetragene lebenspartnerschaft',
      'eingetragenen lebenspartnerschaft',
      'gay',
      'heterosexuell',
      'heterosexueller',
      'heterosexuelle',
      'homosexuell',
      'homosexueller',
      'homosexuelle',
      'intersexuell',
      'intersexuelle',
      'lebenspartner',
      'lebenspartners',
      'lebenspartnerin',
      'lesbe',
      'lesbisch',
      'lgbt',
      'lgbtq',
      'lsbti',
      'lsbtiq',
      'pansexuell',
      'pansexueller',
      'pansexuelle',
      'queer',
      'schwul',
      'schwuler',
      'sexuell aktiv',
      'sexuelle ausrichtung',
      'sexuellen ausrichtung',
      'sexuelle orientierung',
      'sexuellen orientierung',
      'transgender',
      // --- genetic data ---
      'genetischer test',
      'genetischen tests',
      'gentest',
      'gentests',
      'dna-test',
      'dna-tests',
      'dna-analyse',
      'erbgut-analyse',
      'genetisches screening',
      'genetischen screenings',
      'genetische untersuchung',
      'genetischer untersuchung',
      'erbliche veranlagung',
      'erblicher veranlagung',
      'genetische veranlagung',
      'genetischer veranlagung',
      'chromosomenanalyse',
      'genomsequenzierung',
      'vaterschaftstest',
      'vaterschaftstests',
      'abstammungsgutachten',
      'abstammungsgutachtens',
      'genetischer fingerabdruck',
      'genetischen fingerabdrucks',
      'trägerstatus',
      'genetisches profil',
      'genetischen profils',
      'dna-profil',
      'dna-profils',
      'genetische daten',
      'genetischer daten',
    ],
  },
  personReferences: [
    'ich',
    'du',
    'er',
    'sie',
    'schüler',
    'schülerin',
    'student',
    'studentin',
    'kind',
    'nutzer',
    'nutzerin',
    'profil',
  ],
  possessiveDeterminers: [
    'sein',
    'seine',
    'ihr',
    'ihre',
    'mein',
    'meine',
    'dein',
    'deine',
    'des schülers',
    'des kindes',
    'des nutzers',
  ],
  attributionPhrases: [
    'hat',
    'habe',
    'hast',
    'haben',
    'hatte',
    'ist',
    'bin',
    'bist',
    'sind',
    'war',
    'wurde diagnostiziert mit',
    'wurde mit',
    'zeigt anzeichen von',
    'könnte haben',
    'hat wahrscheinlich',
    'hat vermutlich',
    'hat möglicherweise',
  ],
  inferenceMarkers: [
    'könnte',
    'wahrscheinlich',
    'vermutlich',
    'möglicherweise',
    'scheint',
    'anzeichen',
    'verdacht',
  ],
  determiners: ['ein', 'eine', 'einen', 'der', 'die', 'das'],
  scriptHasCase: true,
};

const IT: LanguageCorpus = {
  language: 'it',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'adhd',
      'ddai',
      'autismo',
      'autistico',
      'autistica',
      'disturbo dello spettro autistico',
      'dislessia',
      'dislessico',
      'dislessica',
      'discalculia',
      "disturbo dell'apprendimento",
      "disturbi dell'apprendimento",
      'difficoltà di apprendimento',
      'disturbo specifico di apprendimento',
      'disturbo di salute mentale',
      'malattia mentale',
      'disabilità fisica',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'rom',
      'sinto',
      'sinta',
      'sinti',
      'sinte',
      'curdo',
      'curda',
      'curdi',
      'curde',
      'indigeno',
      'indigena',
      'indigeni',
      'indigene',
      'aborigeno',
      'aborigena',
      'aborigeni',
      'aborigene',
      'meticcio',
      'meticcia',
      'meticci',
      'meticce',
      'mulatto',
      'mulatta',
      'mulatti',
      'mulatte',
      'creolo',
      'creola',
      'creoli',
      'creole',
      'etnia',
      'etnie',
      'di etnia',
      'di origine mista',
      'di origine immigrata',
      'minoranza etnica',
      'minoranze etniche',
      // --- political opinions or affiliation ---
      'comunista',
      'comunisti',
      'comuniste',
      'socialista',
      'socialisti',
      'socialiste',
      'anarchico',
      'anarchica',
      'anarchici',
      'anarchiche',
      'nazionalista',
      'nazionalisti',
      'nazionaliste',
      'femminista',
      'femministi',
      'femministe',
      'fascista',
      'fascisti',
      'fasciste',
      'di destra',
      'di sinistra',
      'di estrema destra',
      'di estrema sinistra',
      'iscritto al partito',
      'iscritta al partito',
      'iscritti al partito',
      'iscritte al partito',
      'opinioni politiche',
      'leghista',
      'leghisti',
      'leghiste',
      'democristiano',
      'democristiana',
      'democristiani',
      'democristiane',
      // --- religious or philosophical beliefs ---
      'cattolico',
      'cattolica',
      'cattolici',
      'cattoliche',
      'protestante',
      'protestanti',
      'musulmano',
      'musulmana',
      'musulmani',
      'musulmane',
      'ebreo',
      'ebrea',
      'ebrei',
      'ebree',
      'induista',
      'induisti',
      'induiste',
      'buddista',
      'buddisti',
      'buddiste',
      'ateo',
      'atea',
      'atei',
      'atee',
      'agnostico',
      'agnostica',
      'agnostici',
      'agnostiche',
      'sciita',
      'sciiti',
      'sciite',
      'sunnita',
      'sunniti',
      'sunnite',
      'mormone',
      'mormoni',
      'testimone di geova',
      'testimoni di geova',
      "convertito all'islam",
      "convertita all'islam",
      "convertiti all'islam",
      "convertite all'islam",
      'hijab',
      'kippah',
      'credo religioso',
      'fede religiosa',
      // --- trade-union membership ---
      'sindacalista',
      'sindacalisti',
      'sindacaliste',
      'iscritto al sindacato',
      'iscritta al sindacato',
      'iscritti al sindacato',
      'iscritte al sindacato',
      'sindacalizzato',
      'sindacalizzata',
      'sindacalizzati',
      'sindacalizzate',
      'delegato sindacale',
      'delegata sindacale',
      'delegati sindacali',
      'delegate sindacali',
      'membro del sindacato',
      'membri del sindacato',
      'attivista sindacale',
      'attivisti sindacali',
      'attiviste sindacali',
      'tessera sindacale',
      'tessere sindacali',
      'contributo sindacale',
      'contributi sindacali',
      // --- sex life or sexual orientation ---
      'gay',
      'lesbica',
      'lesbiche',
      'lesbico',
      'lesbici',
      'bisessuale',
      'bisessuali',
      'pansessuale',
      'pansessuali',
      'queer',
      'omosessuale',
      'omosessuali',
      'eterosessuale',
      'eterosessuali',
      'etero',
      'etera',
      'lgbt',
      'lgbtq',
      'transgender',
      'transessuale',
      'transessuali',
      'intersessuale',
      'intersessuali',
      'orientamento sessuale',
      'sessualmente attivo',
      'sessualmente attiva',
      'sessualmente attivi',
      'sessualmente attive',
      // --- genetic data ---
      'analisi genetica',
      'analisi genetiche',
      'condizione ereditaria',
      'condizioni ereditarie',
      'consulenza genetica',
      'consulenze genetiche',
      'esame genetico',
      'esami genetici',
      'malattia ereditaria',
      'malattie ereditarie',
      'mappatura genetica',
      'mappature genetiche',
      'mutazione genetica',
      'mutazioni genetiche',
      'portatore sano',
      'portatrice sana',
      'portatori sani',
      'portatrici sane',
      'predisposizione genetica',
      'predisposizioni genetiche',
      'profilo genetico',
      'profili genetici',
      'risultato del test genetico',
      'risultati del test genetico',
      'screening genetico',
      'screening genetici',
      'sequenziamento del dna',
      'sequenziamento genetico',
      'test del dna',
      'test genetico',
      'test genetici',
    ],
  },
  personReferences: [
    'io',
    'tu',
    'lui',
    'lei',
    'loro',
    'alunno',
    'alunna',
    'studente',
    'studentessa',
    'bambino',
    'bambina',
    'utente',
    'profilo',
  ],
  possessiveDeterminers: [
    'suo',
    'sua',
    'suoi',
    'sue',
    'mio',
    'mia',
    'tuo',
    'tua',
    "dell'alunno",
    'dello studente',
    'del bambino',
    "dell'utente",
  ],
  attributionPhrases: [
    'ha',
    'ho',
    'hai',
    'hanno',
    'aveva',
    'è',
    'sono',
    'sei',
    'era',
    'è stato diagnosticato con',
    'è stata diagnosticata con',
    'mostra segni di',
    'potrebbe avere',
    'ha probabilmente',
    'ha forse',
  ],
  inferenceMarkers: [
    'potrebbe',
    'probabilmente',
    'forse',
    'possibilmente',
    'sembra',
    'segni di',
    'sospetto',
  ],
  determiners: ['un', 'una', 'il', 'la', 'lo'],
  scriptHasCase: true,
};

const PT: LanguageCorpus = {
  language: 'pt',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'tdah',
      'adhd',
      'autismo',
      'autista',
      'transtorno do espectro autista',
      'dislexia',
      'disléxico',
      'disléxica',
      'discalculia',
      'transtorno de aprendizagem',
      'transtornos de aprendizagem',
      'dificuldade de aprendizagem',
      'dificuldades de aprendizagem',
      'distúrbio de aprendizagem',
      'transtorno de saúde mental',
      'doença mental',
      'deficiência física',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'cigano',
      'cigana',
      'ciganos',
      'ciganas',
      'roma',
      'romas',
      'sinti',
      'sintis',
      'curdo',
      'curda',
      'curdos',
      'curdas',
      'indígena',
      'indígenas',
      'mestiço',
      'mestiça',
      'mestiços',
      'mestiças',
      'pardo',
      'parda',
      'pardos',
      'pardas',
      'quilombola',
      'quilombolas',
      'minoria étnica',
      'minorias étnicas',
      'de herança mista',
      'de origem imigrante',
      'etnia',
      'etnias',
      // --- political opinions or affiliation ---
      'comunista',
      'comunistas',
      'socialista',
      'socialistas',
      'anarquista',
      'anarquistas',
      'nacionalista',
      'nacionalistas',
      'feminista',
      'feministas',
      'fascista',
      'fascistas',
      'capitalista',
      'capitalistas',
      'monarquista',
      'monarquistas',
      'marxista',
      'marxistas',
      'ativista',
      'ativistas',
      'republicano',
      'republicana',
      'republicanos',
      'republicanas',
      'esquerdista',
      'esquerdistas',
      'direitista',
      'direitistas',
      'filiado',
      'filiada',
      'filiados',
      'filiadas',
      'opinião política',
      'opiniões políticas',
      // --- religious or philosophical beliefs ---
      'católico',
      'católica',
      'católicos',
      'católicas',
      'protestante',
      'protestantes',
      'muçulmano',
      'muçulmana',
      'muçulmanos',
      'muçulmanas',
      'judeu',
      'judia',
      'judeus',
      'judias',
      'hindu',
      'hindus',
      'budista',
      'budistas',
      'ateu',
      'ateia',
      'ateus',
      'ateias',
      'agnóstico',
      'agnóstica',
      'agnósticos',
      'agnósticas',
      'devoto',
      'devota',
      'crença religiosa',
      'crenças religiosas',
      'convertido ao islamismo',
      'convertida ao islamismo',
      'hijab',
      'kippah',
      'quipá',
      // --- trade-union membership ---
      'membro do sindicato',
      'membros do sindicato',
      'filiado no sindicato',
      'filiada no sindicato',
      'filiados no sindicato',
      'filiadas no sindicato',
      'sindicalizado',
      'sindicalizada',
      'sindicalizados',
      'sindicalizadas',
      'sindicalista',
      'sindicalistas',
      'delegado sindical',
      'delegada sindical',
      'delegados sindicais',
      'delegadas sindicais',
      'contribuição sindical',
      'contribuições sindicais',
      'quotas sindicais',
      'membro de um sindicato',
      // --- sex life or sexual orientation ---
      'gay',
      'gays',
      'lésbica',
      'lésbicas',
      'bissexual',
      'bissexuais',
      'pansexual',
      'pansexuais',
      'queer',
      'homossexual',
      'homossexuais',
      'heterossexual',
      'heterossexuais',
      'homoafetivo',
      'homoafetiva',
      'homoafetivos',
      'homoafetivas',
      'lgbt',
      'lgbtq',
      'lgbtqia+',
      'transgénero',
      'transgéneros',
      'intersexo',
      'intersexual',
      'intersexuais',
      'orientação sexual',
      'sexualmente ativo',
      'sexualmente ativa',
      'sexualmente ativos',
      'sexualmente ativas',
      // --- genetic data ---
      'análise genética',
      'análises genéticas',
      'condição hereditária',
      'condições hereditárias',
      'dado genético',
      'dados genéticos',
      'doença hereditária',
      'doenças hereditárias',
      'informação genética',
      'informações genéticas',
      'marcador genético',
      'marcadores genéticos',
      'mutação genética',
      'mutações genéticas',
      'perfil genético',
      'perfis genéticos',
      'predisposição genética',
      'predisposições genéticas',
      'rastreio genético',
      'rastreios genéticos',
      'risco genético',
      'riscos genéticos',
      'risco hereditário',
      'riscos hereditários',
      'sequenciamento genético',
      'sequenciamentos genéticos',
      'teste de adn',
      'testes de adn',
      'teste genético',
      'testes genéticos',
      'triagem genética',
      'triagens genéticas',
    ],
  },
  personReferences: [
    'eu',
    'tu',
    'você',
    'ele',
    'ela',
    'eles',
    'aluno',
    'aluna',
    'estudante',
    'criança',
    'usuário',
    'utilizador',
    'perfil',
  ],
  possessiveDeterminers: [
    'seu',
    'sua',
    'seus',
    'suas',
    'meu',
    'minha',
    'do aluno',
    'da aluna',
    'do estudante',
    'da criança',
    'do usuário',
  ],
  attributionPhrases: [
    'tem',
    'tenho',
    'tens',
    'têm',
    'tinha',
    'é',
    'sou',
    'és',
    'são',
    'era',
    'foi diagnosticado com',
    'foi diagnosticada com',
    'apresenta sinais de',
    'pode ter',
    'poderia ter',
    'provavelmente tem',
    'possivelmente tem',
  ],
  inferenceMarkers: [
    'pode',
    'poderia',
    'provavelmente',
    'possivelmente',
    'parece',
    'apresenta sinais',
    'suspeita',
  ],
  determiners: ['um', 'uma', 'o', 'a'],
  scriptHasCase: true,
};

const PL: LanguageCorpus = {
  language: 'pl',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'adhd',
      'autyzm',
      'autyzmu',
      'autystyczny',
      'autystyczna',
      'autystyczne',
      'autysta',
      'spektrum autyzmu',
      'dysleksja',
      'dysleksję',
      'dysleksji',
      'dyslektyk',
      'dyslektyczka',
      'dyskalkulia',
      'dyskalkulię',
      'dyskalkulii',
      'trudności w uczeniu się',
      'trudności w nauce',
      'zaburzenia uczenia się',
      'niepełnosprawność intelektualna',
      'choroba psychiczna',
      'chorobę psychiczną',
      'zaburzenie psychiczne',
      'niepełnosprawność fizyczna',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'rom',
      'roma',
      'romem',
      'romka',
      'romki',
      'romkę',
      'romką',
      'kurd',
      'kurda',
      'kurdem',
      'kurdyjka',
      'kurdyjki',
      'kurdyjkę',
      'kurdyjką',
      'metys',
      'metysa',
      'metysem',
      'metyska',
      'metyski',
      'metyską',
      'rdzenny',
      'rdzenna',
      'rdzennym',
      'rdzenną',
      'mieszane pochodzenie',
      'mieszanego pochodzenia',
      'mieszanym pochodzeniem',
      'mniejszość etniczna',
      'mniejszości etnicznej',
      'mniejszość etniczną',
      'mniejszością etniczną',
      'narodowość',
      'narodowością',
      'etniczność',
      'etnicznością',
      // --- political opinions or affiliation ---
      'komunista',
      'komunisty',
      'komunistę',
      'komunistą',
      'komunistka',
      'komunistki',
      'komunistkę',
      'komunistką',
      'socjalista',
      'socjalisty',
      'socjalistę',
      'socjalistą',
      'socjalistka',
      'socjalistki',
      'socjalistkę',
      'socjalistką',
      'nacjonalista',
      'nacjonalisty',
      'nacjonalistę',
      'nacjonalistą',
      'nacjonalistka',
      'nacjonalistki',
      'nacjonalistkę',
      'nacjonalistką',
      'członek partii',
      'członka partii',
      'członkiem partii',
      'członkini partii',
      'członkinię partii',
      'członkinią partii',
      'poglądy polityczne',
      'poglądów politycznych',
      'poglądami politycznymi',
      // --- religious or philosophical beliefs ---
      'katolik',
      'katolika',
      'katolikiem',
      'katoliczka',
      'katoliczki',
      'katoliczkę',
      'katoliczką',
      'muzułmanin',
      'muzułmanina',
      'muzułmaninem',
      'muzułmanka',
      'muzułmanki',
      'muzułmankę',
      'muzułmanką',
      'żyd',
      'żyda',
      'żydem',
      'żydówka',
      'żydówki',
      'żydówkę',
      'żydówką',
      'ateista',
      'ateisty',
      'ateistę',
      'ateistą',
      'ateistka',
      'ateistki',
      'ateistkę',
      'ateistką',
      'prawosławny',
      'prawosławnego',
      'prawosławnym',
      'prawosławna',
      'prawosławnej',
      'prawosławną',
      'hidżab',
      'hidżabu',
      'hidżabem',
      'jarmułka',
      'jarmułki',
      'jarmułkę',
      'jarmułką',
      // --- trade-union membership ---
      'związkowiec',
      'związkowca',
      'związkowcem',
      'związkowczyni',
      'związkowczynią',
      'członek związku zawodowego',
      'członka związku zawodowego',
      'członkiem związku zawodowego',
      'członkini związku zawodowego',
      'członkinię związku zawodowego',
      'członkinią związku zawodowego',
      'działacz związkowy',
      'działacza związkowego',
      'działaczem związkowym',
      'działaczka związkowa',
      'działaczki związkowej',
      'działaczkę związkową',
      'działaczką związkową',
      'mąż zaufania',
      'męża zaufania',
      'mężem zaufania',
      'składki związkowe',
      'składek związkowych',
      'składkami związkowymi',
      'uzwiązkowiony',
      'uzwiązkowiona',
      'członkostwo w związku zawodowym',
      'członkostwa w związku zawodowym',
      'członkostwem w związku zawodowym',
      // --- sex life or sexual orientation ---
      'gej',
      'geja',
      'gejem',
      'lesbijka',
      'lesbijki',
      'lesbijkę',
      'lesbijką',
      'biseksualny',
      'biseksualnego',
      'biseksualnym',
      'biseksualna',
      'biseksualnej',
      'biseksualną',
      'panseksualny',
      'panseksualnego',
      'panseksualnym',
      'panseksualna',
      'panseksualnej',
      'panseksualną',
      'queer',
      'lgbtq',
      'transpłciowy',
      'transpłciowego',
      'transpłciowym',
      'transpłciowa',
      'transpłciowej',
      'transpłciową',
      'orientacja seksualna',
      'orientacji seksualnej',
      'orientację seksualną',
      'orientacją seksualną',
      // --- genetic data ---
      'test genetyczny',
      'testu genetycznego',
      'testem genetycznym',
      'badanie genetyczne',
      'badania genetycznego',
      'badaniem genetycznym',
      'choroba genetyczna',
      'choroby genetycznej',
      'chorobę genetyczną',
      'chorobą genetyczną',
      'choroba dziedziczna',
      'choroby dziedzicznej',
      'chorobę dziedziczną',
      'chorobą dziedziczną',
      'obciążenie genetyczne',
      'obciążenia genetycznego',
      'obciążeniem genetycznym',
      'mutacja genetyczna',
      'mutacji genetycznej',
      'mutację genetyczną',
      'mutacją genetyczną',
      'nosicielstwo genu',
      'nosicielstwa genu',
      'nosicielstwem genu',
      'wynik testu dna',
      'wyniku testu dna',
      'wynikiem testu dna',
    ],
  },
  personReferences: [
    'ja',
    'ty',
    'on',
    'ona',
    'oni',
    'uczeń',
    'uczennica',
    'student',
    'studentka',
    'dziecko',
    'użytkownik',
    'profil',
  ],
  possessiveDeterminers: [
    'jego',
    'jej',
    'ich',
    'mój',
    'moja',
    'twój',
    'twoja',
    'ucznia',
    'uczennicy',
    'dziecka',
    'użytkownika',
  ],
  attributionPhrases: [
    'ma',
    'mam',
    'masz',
    'mają',
    'miał',
    'miała',
    'jest',
    'jestem',
    'jesteś',
    'są',
    'był',
    'była',
    'został zdiagnozowany',
    'została zdiagnozowana',
    'wykazuje objawy',
    'prawdopodobnie ma',
    'możliwe że ma',
  ],
  inferenceMarkers: [
    'prawdopodobnie',
    'możliwe',
    'być może',
    'wydaje się',
    'objawy',
    'podejrzenie',
  ],
  determiners: [],
  scriptHasCase: true,
};

const JA: LanguageCorpus = {
  language: 'ja',
  confidence: 'model-generated',
  // Japanese needs explicit SCRIPT VARIATION, not just NFKC: NFKC folds
  // half-width/full-width (ＡＤＨＤ -> ADHD, ｱｽﾍﾟﾙｶﾞｰ -> アスペルガー) but does
  // NOT bridge kanji <-> katakana <-> romaji. Those are separate entries.
  lexemes: {
    broad: [
      'adhd',
      '注意欠陥多動性障害',
      '注意欠如多動症',
      '注意欠如・多動症',
      'エーディーエイチディー',
      '自閉症',
      '自閉スペクトラム症',
      '自閉症スペクトラム',
      'asd',
      'アスペルガー',
      'アスペルガー症候群',
      '発達障害',
      '発達障がい',
      'ディスレクシア',
      '失読症',
      '読字障害',
      'dyslexia',
      '学習障害',
      '学習障がい',
      'ディスカリキュリア',
      '算数障害',
      '精神疾患',
      '精神障害',
      '身体障害',
      '身体障がい',
    ],
    'attributed-only': [],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'アイヌ',
      'シンティ',
      'クルド人',
      '先住民',
      '少数民族',
      '混血',
      '外国にルーツを持つ',
      '移民の背景',
      'ethnic minority',
      'indigenous',
      'immigrant background',
      // --- political opinions or affiliation ---
      '共産主義者',
      'コミュニスト',
      'communist',
      '社会主義者',
      'ソーシャリスト',
      'socialist',
      '無政府主義者',
      'アナキスト',
      'anarchist',
      '国家主義者',
      'ナショナリスト',
      'フェミニスト',
      'feminist',
      'ファシスト',
      'fascist',
      'マルクス主義者',
      '極右',
      '極左',
      '党員',
      '政治的見解',
      '政治思想',
      '政治信条',
      // --- religious or philosophical beliefs ---
      'キリスト教徒',
      'クリスチャン',
      'カトリック教徒',
      'プロテスタント',
      'イスラム教徒',
      'ムスリム',
      'イスラム教に改宗',
      'ヒジャブ',
      'ユダヤ教徒',
      'ユダヤ人',
      'キッパー',
      '仏教徒',
      'ヒンドゥー教徒',
      '神道を信仰',
      '無神論者',
      '不可知論者',
      '無宗教',
      '信心深い',
      '宗教的信条',
      'シーア派',
      'スンニ派',
      '改宗した',
      // --- trade-union membership ---
      '組合員',
      '労働組合員',
      '組合費',
      '労働組合費',
      '職場委員',
      '組合代表',
      '組合役員',
      '執行委員',
      '分会長',
      '組合活動家',
      '労働組合活動家',
      'ユニオンメンバー',
      '組合に加入',
      '労働組合に加入',
      '組合のメンバー',
      '労働組合のメンバー',
      // --- sex life or sexual orientation ---
      'ゲイ',
      'gay',
      'レズビアン',
      'lesbian',
      'バイセクシャル',
      'bisexual',
      '両性愛',
      'パンセクシャル',
      'pansexual',
      'クィア',
      'queer',
      '同性愛',
      'ホモセクシュアル',
      'homosexual',
      '異性愛',
      'ヘテロセクシュアル',
      'heterosexual',
      'LGBT',
      'LGBTQ',
      'トランスジェンダー',
      'transgender',
      'インターセックス',
      'intersex',
      '性的指向',
      'ノンバイナリー',
      'non-binary',
      'Xジェンダー',
      'セクマイ',
      '性的マイノリティ',
      // --- genetic data ---
      '遺伝子検査',
      '遺伝子テスト',
      'dna検査',
      'dnaテスト',
      'dna test',
      '遺伝子スクリーニング',
      '遺伝子解析',
      'dna解析',
      'dna鑑定',
      '遺伝子配列',
      '遺伝性疾患',
      '遺伝病',
      '遺伝的素因',
      '遺伝的体質',
      '遺伝子検査の結果',
    ],
  },
  personReferences: [
    '私',
    'わたし',
    'あなた',
    '彼',
    '彼女',
    '学習者',
    '生徒',
    '児童',
    '学生',
    '子ども',
    '子供',
    'ユーザー',
    'プロフィール',
  ],
  possessiveDeterminers: [],
  attributionPhrases: [],
  inferenceMarkers: [
    'かもしれない',
    'おそらく',
    'たぶん',
    '疑い',
    '傾向',
    'ようだ',
    'と思われる',
  ],
  determiners: [],
  // No letter case — the Latin "capitalized token = person name" heuristic is
  // inapplicable and is NOT used. Named attribution is detected structurally
  // instead, via the topic/possessive particles and honorific suffixes below.
  scriptHasCase: false,
  // `PERSON` expands to the personReferences alternation, `LEX` to the full
  // lexeme alternation. The subject is deliberately restricted to a person
  // reference or an honorific-marked name — an earlier draft accepted ANY
  // preceding CJK token before は/の, which false-fired on ordinary
  // educational prose ("この章では…失読症…" — "in this chapter … dyslexia").
  rawAttributionPatterns: [
    // "<person reference>は/の/には … <lexeme>" within one clause.
    String.raw`PERSON(?:は|の|には)[^。！？\n]{0,24}?LEX`,
    // "<name>さん/くん/ちゃん(は|の) … <lexeme>" — the honorific marks a person,
    // in either script (Japanese or a Latin-script name in mixed prose).
    String.raw`[\p{Script=Han}\p{Script=Katakana}\p{Script=Hiragana}\p{L}]{1,12}(?:さん|くん|ちゃん|君)(?:は|の|には)?[^。！？\n]{0,24}?LEX`,
  ],
};

const NB: LanguageCorpus = {
  language: 'nb',
  confidence: 'model-generated',
  lexemes: {
    broad: [
      'adhd',
      // NOTE: Norwegian "ADD" is not broad — homograph of English "add". It sits
      // in this corpus's 'attributed-only' scope: `Eleven har ADD` blocks, a bare
      // "add" never fires.
      'autisme',
      'autistisk',
      'autist',
      'autismespekterforstyrrelse',
      'dysleksi',
      'dyslektiker',
      'dyslektisk',
      'ordblind',
      'ordblindhet',
      'dyskalkuli',
      'lærevansker',
      'lærevanske',
      'lese- og skrivevansker',
      'psykisk lidelse',
      'psykisk sykdom',
      'fysisk funksjonsnedsettelse',
      'funksjonsnedsettelse',
    ],
    'attributed-only': ['add'],
    'unnamed-attribution-only': [
      // --- racial or ethnic origin ---
      'romen',
      'romer',
      'romsk',
      'sinti',
      'sintien',
      'sintier',
      'kurder',
      'kurderen',
      'kurdere',
      'kurdisk',
      'samen',
      'samer',
      'samisk',
      'urfolk',
      'urfolket',
      'urfolksbakgrunn',
      'innvandrerbakgrunn',
      'flerkulturell',
      'flerkulturell bakgrunn',
      'blandet bakgrunn',
      'etnisk minoritet',
      'etniske minoriteter',
      'etnisitet',
      'avstamning',
      'herkomst',
      // --- political opinions or affiliation ---
      'kommunist',
      'kommunisten',
      'kommunister',
      'kommunistisk',
      'sosialist',
      'sosialisten',
      'sosialister',
      'sosialistisk',
      'anarkist',
      'anarkisten',
      'anarkister',
      'anarkistisk',
      'nasjonalist',
      'nasjonalisten',
      'nasjonalister',
      'nasjonalistisk',
      'feminist',
      'feministen',
      'feminister',
      'feministisk',
      'høyreekstremist',
      'høyreekstremisten',
      'høyreekstremister',
      'høyreekstrem',
      'partimedlem',
      'partimedlemmet',
      'partimedlemmer',
      'politiske syn',
      'politiske holdninger',
      // --- religious or philosophical beliefs ---
      'ateist',
      'ateisten',
      'ateister',
      'agnostiker',
      'agnostikeren',
      'agnostikere',
      'buddhist',
      'buddhisten',
      'buddhister',
      'hindu',
      'hinduen',
      'hinduer',
      'jøde',
      'jøden',
      'jøder',
      'katolikk',
      'katolikken',
      'katolikker',
      'muslim',
      'muslimen',
      'muslimer',
      'protestant',
      'protestanten',
      'protestanter',
      'kristen',
      'kristne',
      'agnostisk',
      'ateistisk',
      'buddhistisk',
      'hinduistisk',
      'jødisk',
      'katolsk',
      'muslimsk',
      'protestantisk',
      'religiøs',
      'hijab',
      'hijaben',
      'kippa',
      'kippaen',
      'livssyn',
      'livssynet',
      'religion',
      'religionen',
      'tro',
      'troen',
      // --- trade-union membership ---
      'fagforeningsmedlem',
      'fagforeningsmedlemmet',
      'fagforeningsmedlemmer',
      'fagforeningsmedlemmene',
      'fagorganisert',
      'uorganisert',
      'tillitsvalgt',
      'tillitsvalgte',
      'hovedtillitsvalgt',
      'hovedtillitsvalgte',
      'plasstillitsvalgt',
      'plasstillitsvalgte',
      'streikevakt',
      'streikevakten',
      'streikevakter',
      'streikevaktene',
      'fagforeningskontingent',
      'fagforeningskontingenten',
      'medlem av en fagforening',
      'medlem av fagforeningen',
      // --- sex life or sexual orientation ---
      'homofil',
      'homofilen',
      'homofile',
      'lesbisk',
      'lesbiske',
      'bifil',
      'bifilen',
      'bifile',
      'panfil',
      'panfilen',
      'panfile',
      'gay',
      'queer',
      'homoseksuell',
      'homoseksuelle',
      'heterofil',
      'heterofilen',
      'heterofile',
      'heteroseksuell',
      'heteroseksuelle',
      'lhbt',
      'lhbtq',
      'lhbtiq',
      'lgbt',
      'lgbtq',
      'transperson',
      'transpersonen',
      'transpersoner',
      'transkjønnet',
      'interkjønn',
      'seksuell legning',
      'seksuelle legning',
      'seksuelle legninger',
      'seksuell orientering',
      'seksuelle orientering',
      'seksuelle orienteringer',
      'seksuelt aktiv',
      'seksuelt aktive',
      // --- genetic data ---
      'genetisk test',
      'genetiske testen',
      'genetiske tester',
      'dna-test',
      'dna-testen',
      'dna-tester',
      'gentest',
      'gentesten',
      'gentester',
      'genetisk analyse',
      'genetiske analysen',
      'genetiske analyser',
      'arvelig tilstand',
      'arvelige tilstanden',
      'arvelige tilstander',
      'arvelig sykdom',
      'arvelige sykdommen',
      'arvelige sykdommer',
      'genfeil',
      'genfeilen',
      'kromosomfeil',
      'kromosomfeilen',
      'genetisk screening',
      'genetiske screeningen',
      'genetiske screeninger',
      'genetisk kartlegging',
      'genetiske kartleggingen',
      'genetiske kartlegginger',
      'arvelig belastning',
      'arvelige belastningen',
      'arvelige belastninger',
      'mutasjon',
      'mutasjonen',
      'mutasjoner',
    ],
  },
  personReferences: [
    'jeg',
    'du',
    'han',
    'hun',
    'de',
    'eleven',
    'elev',
    'student',
    'barnet',
    'barn',
    'bruker',
    'brukeren',
    'profil',
  ],
  possessiveDeterminers: [
    'hans',
    'hennes',
    'deres',
    'min',
    'mitt',
    'din',
    'ditt',
    'elevens',
    'barnets',
    'brukerens',
  ],
  attributionPhrases: [
    'har',
    'hadde',
    'er',
    'var',
    'ble diagnostisert med',
    'har fått diagnosen',
    'viser tegn på',
    'kan ha',
    'har sannsynligvis',
    'har muligens',
  ],
  inferenceMarkers: [
    'kan',
    'sannsynligvis',
    'muligens',
    'kanskje',
    'ser ut',
    'tegn på',
    'mistanke',
  ],
  determiners: ['en', 'ei', 'et', 'den', 'det'],
  scriptHasCase: true,
};

export const LANGUAGE_CORPORA: Readonly<
  Record<ConversationLanguage, LanguageCorpus>
> = {
  en: EN,
  cs: CS,
  es: ES,
  fr: FR,
  de: DE,
  it: IT,
  pt: PT,
  pl: PL,
  ja: JA,
  nb: NB,
};

export const CORPUS_LANGUAGES = Object.keys(
  LANGUAGE_CORPORA,
) as readonly ConversationLanguage[];
