// ---------------------------------------------------------------------------
// [WI-2628] Protected-lexeme corpus for the shared multilingual persisted-
// learning-text safety gate (MMT-ADR-0036 §4.6, Alternative 10 rejected the
// English-regex-at-each-caller design this replaces).
//
// SCOPE DISCIPLINE — the corpus names *conditions*, and the grammar around it
// names *attribution*. Mere mention of a condition is NOT a block: the gate
// blocks person-attributed clinical text. `apps/api/eval-llm/fixtures/probes/
// battery.ts` line ~999 deliberately contains "ADHD-style short-burst
// support" — legitimate personalization language that must never be a block.
//
// CONFIDENCE IS RECORDED IN THE DATA, NOT ONLY IN A REPORT. `confidence` is
// 'reviewed' only for the English set, which is a direct port of the shipped,
// Art-9-decision-scoped list in persisted-learning-text-guard.ts. Every other
// language is 'model-generated' and REQUIRES native-speaker review before it
// can be relied on as a compliance control. Under-claim, never over-claim.
//
// Every entry is a LITERAL phrase (regex metacharacters are escaped by the
// scanner; internal spaces become flexible whitespace). Inflected forms are
// listed explicitly rather than approximated by a bare stem — a bare stem both
// over-fires (matching unrelated words) and under-fires (missing case endings).
// ---------------------------------------------------------------------------

import type { ConversationLanguage } from '@eduagent/schemas';

export type CorpusConfidence = 'reviewed' | 'model-generated';

export interface LanguageCorpus {
  readonly language: ConversationLanguage;
  /** 'reviewed' = expert-validated. 'model-generated' = needs native review. */
  readonly confidence: CorpusConfidence;
  /** Condition / diagnosis terms. Contribute the "protected lexeme present" signal. */
  readonly lexemes: readonly string[];
  /** Generic person references (pronouns, learner roles) usable as an attribution subject. */
  readonly personReferences: readonly string[];
  /** Possessive determiners: "<det> <lexeme>" is attribution without a verb. */
  readonly possessiveDeterminers: readonly string[];
  /** Attribution verbs / phrases linking a person to a lexeme. */
  readonly attributionPhrases: readonly string[];
  /** Hedges that make an attribution an *inference* rather than an assertion. */
  readonly inferenceMarkers: readonly string[];
  /** Articles/quantifiers tolerated between the verb and the lexeme. */
  readonly determiners: readonly string[];
  /**
   * Whether the script has letter case. When false the "capitalized token =
   * person name" heuristic used for Latin scripts is meaningless and MUST NOT
   * be applied — see `rawAttributionPatterns`.
   */
  readonly scriptHasCase: boolean;
  /**
   * Raw regex sources (NOT escaped) for scripts without case or word
   * boundaries. `LEX` is substituted with the full lexeme alternation.
   */
  readonly rawAttributionPatterns?: readonly string[];
}

const EN: LanguageCorpus = {
  language: 'en',
  // Direct port of the shipped WI-1195 Art-9 list — the only expert-scoped set.
  confidence: 'reviewed',
  lexemes: [
    'adhd',
    'autism',
    'autistic',
    'dyslexia',
    'dyslexic',
    'dyscalculia',
    'dyscalculic',
    'learning disability',
    'learning disabilities',
    // Hyphenated compounds, matching how 'mental-health condition' is already
    // carried. Without these, "a learning-disability diagnosis" scanned clear
    // while the space-separated form blocked.
    'learning-disability',
    'learning-disabilities',
    'mental health condition',
    'mental-health condition',
    'physical health condition',
    'physical-health condition',
  ],
  personReferences: [
    'i',
    'you',
    'learner',
    'student',
    'child',
    'user',
    'profile',
    'they',
    'he',
    'she',
  ],
  possessiveDeterminers: [
    'learner',
    'student',
    'child',
    'user',
    'profile',
    'their',
    'his',
    'her',
    'your',
    'my',
  ],
  attributionPhrases: [
    'may have',
    'might have',
    'could have',
    'likely has',
    'appears to have',
    'seems to have',
    'shows signs of',
    'is diagnosed with',
    'was diagnosed with',
    'were diagnosed with',
    'has',
    'have',
    'had',
    'is',
    'am',
    'are',
    'was',
    'were',
  ],
  inferenceMarkers: [
    'may',
    'might',
    'could',
    'likely',
    'probably',
    'possibly',
    'suspected',
    'appears',
    'seems',
    'signs of',
  ],
  determiners: ['a', 'an', 'the'],
  scriptHasCase: true,
};

const CS: LanguageCorpus = {
  language: 'cs',
  confidence: 'model-generated',
  lexemes: [
    'adhd',
    // Czech declines: nominative/genitive/dative/instrumental forms listed.
    'autismus',
    'autismu',
    'autismem',
    'autista',
    'autisty',
    'autistou',
    'autistický',
    'autistická',
    'autistické',
    'autistického',
    'autistickou',
    'dyslexie',
    'dyslexii',
    'dyslexií',
    'dyslektik',
    'dyslektika',
    'dyslektický',
    'dyslektická',
    'dyskalkulie',
    'dyskalkulii',
    'dyskalkulií',
    'dyskalkulik',
    'porucha učení',
    'poruchu učení',
    'poruchou učení',
    'poruchy učení',
    'specifická porucha učení',
    'duševní onemocnění',
    'duševní porucha',
    'duševní poruchu',
    'psychické onemocnění',
    'tělesné postižení',
    'tělesným postižením',
  ],
  personReferences: [
    'já',
    'ty',
    'on',
    'ona',
    'oni',
    'žák',
    'žákyně',
    'student',
    'studentka',
    'dítě',
    'uživatel',
    'profil',
  ],
  possessiveDeterminers: [
    'jeho',
    'její',
    'jejich',
    'můj',
    'moje',
    'tvůj',
    'tvoje',
    'žákova',
    'žákovo',
    'studentova',
    'dítěte',
    'uživatele',
  ],
  attributionPhrases: [
    'má',
    'mám',
    'máš',
    'mají',
    'měl',
    'měla',
    'je',
    'jsem',
    'jsi',
    'jsou',
    'byl',
    'byla',
    'byl diagnostikován',
    'byla diagnostikována',
    'má diagnózu',
    'jeví známky',
    'pravděpodobně má',
    'možná má',
  ],
  inferenceMarkers: [
    'pravděpodobně',
    'možná',
    'asi',
    'zdá se',
    'jeví známky',
    'podezření',
    'suspektní',
  ],
  determiners: [],
  scriptHasCase: true,
};

const ES: LanguageCorpus = {
  language: 'es',
  confidence: 'model-generated',
  lexemes: [
    'tdah',
    'adhd',
    'autismo',
    'autista',
    'trastorno del espectro autista',
    // NOTE: the Spanish acronym "TEA" is deliberately OMITTED — it is the
    // English word "tea", and lexeme detection runs across all ten languages.
    'dislexia',
    'disléxico',
    'disléxica',
    'discalculia',
    'trastorno de aprendizaje',
    'trastornos de aprendizaje',
    'dificultad de aprendizaje',
    'dificultades de aprendizaje',
    'discapacidad de aprendizaje',
    'trastorno de salud mental',
    'enfermedad mental',
    'discapacidad física',
  ],
  personReferences: [
    'yo',
    'tú',
    'él',
    'ella',
    'ellos',
    'usted',
    'el alumno',
    'la alumna',
    'alumno',
    'alumna',
    'estudiante',
    'niño',
    'niña',
    'usuario',
    'perfil',
  ],
  possessiveDeterminers: [
    'su',
    'sus',
    'mi',
    'mis',
    'tu',
    'tus',
    'del alumno',
    'del estudiante',
    'del niño',
    'del usuario',
  ],
  attributionPhrases: [
    'tiene',
    'tengo',
    'tienes',
    'tienen',
    'tenía',
    'es',
    'soy',
    'eres',
    'son',
    'era',
    'fue diagnosticado con',
    'fue diagnosticada con',
    'ha sido diagnosticado con',
    'presenta signos de',
    'puede tener',
    'podría tener',
    'probablemente tiene',
    'posiblemente tiene',
  ],
  inferenceMarkers: [
    'puede',
    'podría',
    'probablemente',
    'posiblemente',
    'parece',
    'presenta signos',
    'sospecha',
  ],
  determiners: ['un', 'una', 'el', 'la'],
  scriptHasCase: true,
};

const FR: LanguageCorpus = {
  language: 'fr',
  confidence: 'model-generated',
  lexemes: [
    'tdah',
    'adhd',
    'autisme',
    'autiste',
    'trouble du spectre autistique',
    'dyslexie',
    'dyslexique',
    'dyscalculie',
    "trouble d'apprentissage",
    "troubles d'apprentissage",
    "difficulté d'apprentissage",
    "difficultés d'apprentissage",
    'trouble de santé mentale',
    'maladie mentale',
    'handicap physique',
  ],
  personReferences: [
    'je',
    'tu',
    'il',
    'elle',
    'ils',
    'vous',
    "l'élève",
    'élève',
    'étudiant',
    'étudiante',
    'enfant',
    'utilisateur',
    'profil',
  ],
  possessiveDeterminers: [
    'son',
    'sa',
    'ses',
    'mon',
    'ma',
    'mes',
    'ton',
    'ta',
    'tes',
    "de l'élève",
    "de l'enfant",
    "de l'utilisateur",
  ],
  attributionPhrases: [
    'a',
    'ai',
    'as',
    'ont',
    'avait',
    'est',
    'suis',
    'es',
    'sont',
    'était',
    'a été diagnostiqué avec',
    'a été diagnostiquée avec',
    'présente des signes de',
    'peut avoir',
    'pourrait avoir',
    'a probablement',
    'a peut-être',
  ],
  inferenceMarkers: [
    'peut',
    'pourrait',
    'probablement',
    'peut-être',
    'semble',
    'présente des signes',
    'soupçon',
  ],
  determiners: ['un', 'une', 'le', 'la', "l'", 'du', 'de la'],
  scriptHasCase: true,
};

const DE: LanguageCorpus = {
  language: 'de',
  confidence: 'model-generated',
  lexemes: [
    'adhs',
    // NOTE: German "ADS" deliberately OMITTED — homograph of English "ads".
    'adhd',
    'autismus',
    'autistisch',
    'autistische',
    'autistischer',
    'autist',
    'autismus-spektrum-störung',
    'legasthenie',
    'legastheniker',
    'legasthenikerin',
    'dyslexie',
    'dyskalkulie',
    'rechenstörung',
    'lernbehinderung',
    'lernstörung',
    'lernstörungen',
    'psychische erkrankung',
    'psychische störung',
    'körperliche behinderung',
  ],
  personReferences: [
    'ich',
    'du',
    'er',
    'sie',
    'schüler',
    'schülerin',
    'student',
    'studentin',
    'kind',
    'nutzer',
    'nutzerin',
    'profil',
  ],
  possessiveDeterminers: [
    'sein',
    'seine',
    'ihr',
    'ihre',
    'mein',
    'meine',
    'dein',
    'deine',
    'des schülers',
    'des kindes',
    'des nutzers',
  ],
  attributionPhrases: [
    'hat',
    'habe',
    'hast',
    'haben',
    'hatte',
    'ist',
    'bin',
    'bist',
    'sind',
    'war',
    'wurde diagnostiziert mit',
    'wurde mit',
    'zeigt anzeichen von',
    'könnte haben',
    'hat wahrscheinlich',
    'hat vermutlich',
    'hat möglicherweise',
  ],
  inferenceMarkers: [
    'könnte',
    'wahrscheinlich',
    'vermutlich',
    'möglicherweise',
    'scheint',
    'anzeichen',
    'verdacht',
  ],
  determiners: ['ein', 'eine', 'einen', 'der', 'die', 'das'],
  scriptHasCase: true,
};

const IT: LanguageCorpus = {
  language: 'it',
  confidence: 'model-generated',
  lexemes: [
    'adhd',
    'ddai',
    'autismo',
    'autistico',
    'autistica',
    'disturbo dello spettro autistico',
    'dislessia',
    'dislessico',
    'dislessica',
    'discalculia',
    "disturbo dell'apprendimento",
    "disturbi dell'apprendimento",
    'difficoltà di apprendimento',
    'disturbo specifico di apprendimento',
    'disturbo di salute mentale',
    'malattia mentale',
    'disabilità fisica',
  ],
  personReferences: [
    'io',
    'tu',
    'lui',
    'lei',
    'loro',
    'alunno',
    'alunna',
    'studente',
    'studentessa',
    'bambino',
    'bambina',
    'utente',
    'profilo',
  ],
  possessiveDeterminers: [
    'suo',
    'sua',
    'suoi',
    'sue',
    'mio',
    'mia',
    'tuo',
    'tua',
    "dell'alunno",
    'dello studente',
    'del bambino',
    "dell'utente",
  ],
  attributionPhrases: [
    'ha',
    'ho',
    'hai',
    'hanno',
    'aveva',
    'è',
    'sono',
    'sei',
    'era',
    'è stato diagnosticato con',
    'è stata diagnosticata con',
    'mostra segni di',
    'potrebbe avere',
    'ha probabilmente',
    'ha forse',
  ],
  inferenceMarkers: [
    'potrebbe',
    'probabilmente',
    'forse',
    'possibilmente',
    'sembra',
    'segni di',
    'sospetto',
  ],
  determiners: ['un', 'una', 'il', 'la', 'lo'],
  scriptHasCase: true,
};

const PT: LanguageCorpus = {
  language: 'pt',
  confidence: 'model-generated',
  lexemes: [
    'tdah',
    'adhd',
    'autismo',
    'autista',
    'transtorno do espectro autista',
    'dislexia',
    'disléxico',
    'disléxica',
    'discalculia',
    'transtorno de aprendizagem',
    'transtornos de aprendizagem',
    'dificuldade de aprendizagem',
    'dificuldades de aprendizagem',
    'distúrbio de aprendizagem',
    'transtorno de saúde mental',
    'doença mental',
    'deficiência física',
  ],
  personReferences: [
    'eu',
    'tu',
    'você',
    'ele',
    'ela',
    'eles',
    'aluno',
    'aluna',
    'estudante',
    'criança',
    'usuário',
    'utilizador',
    'perfil',
  ],
  possessiveDeterminers: [
    'seu',
    'sua',
    'seus',
    'suas',
    'meu',
    'minha',
    'do aluno',
    'da aluna',
    'do estudante',
    'da criança',
    'do usuário',
  ],
  attributionPhrases: [
    'tem',
    'tenho',
    'tens',
    'têm',
    'tinha',
    'é',
    'sou',
    'és',
    'são',
    'era',
    'foi diagnosticado com',
    'foi diagnosticada com',
    'apresenta sinais de',
    'pode ter',
    'poderia ter',
    'provavelmente tem',
    'possivelmente tem',
  ],
  inferenceMarkers: [
    'pode',
    'poderia',
    'provavelmente',
    'possivelmente',
    'parece',
    'apresenta sinais',
    'suspeita',
  ],
  determiners: ['um', 'uma', 'o', 'a'],
  scriptHasCase: true,
};

const PL: LanguageCorpus = {
  language: 'pl',
  confidence: 'model-generated',
  lexemes: [
    'adhd',
    'autyzm',
    'autyzmu',
    'autystyczny',
    'autystyczna',
    'autystyczne',
    'autysta',
    'spektrum autyzmu',
    'dysleksja',
    'dysleksję',
    'dysleksji',
    'dyslektyk',
    'dyslektyczka',
    'dyskalkulia',
    'dyskalkulię',
    'dyskalkulii',
    'trudności w uczeniu się',
    'trudności w nauce',
    'zaburzenia uczenia się',
    'niepełnosprawność intelektualna',
    'choroba psychiczna',
    'chorobę psychiczną',
    'zaburzenie psychiczne',
    'niepełnosprawność fizyczna',
  ],
  personReferences: [
    'ja',
    'ty',
    'on',
    'ona',
    'oni',
    'uczeń',
    'uczennica',
    'student',
    'studentka',
    'dziecko',
    'użytkownik',
    'profil',
  ],
  possessiveDeterminers: [
    'jego',
    'jej',
    'ich',
    'mój',
    'moja',
    'twój',
    'twoja',
    'ucznia',
    'uczennicy',
    'dziecka',
    'użytkownika',
  ],
  attributionPhrases: [
    'ma',
    'mam',
    'masz',
    'mają',
    'miał',
    'miała',
    'jest',
    'jestem',
    'jesteś',
    'są',
    'był',
    'była',
    'został zdiagnozowany',
    'została zdiagnozowana',
    'wykazuje objawy',
    'prawdopodobnie ma',
    'możliwe że ma',
  ],
  inferenceMarkers: [
    'prawdopodobnie',
    'możliwe',
    'być może',
    'wydaje się',
    'objawy',
    'podejrzenie',
  ],
  determiners: [],
  scriptHasCase: true,
};

const JA: LanguageCorpus = {
  language: 'ja',
  confidence: 'model-generated',
  // Japanese needs explicit SCRIPT VARIATION, not just NFKC: NFKC folds
  // half-width/full-width (ＡＤＨＤ -> ADHD, ｱｽﾍﾟﾙｶﾞｰ -> アスペルガー) but does
  // NOT bridge kanji <-> katakana <-> romaji. Those are separate entries.
  lexemes: [
    'adhd',
    '注意欠陥多動性障害',
    '注意欠如多動症',
    '注意欠如・多動症',
    'エーディーエイチディー',
    '自閉症',
    '自閉スペクトラム症',
    '自閉症スペクトラム',
    'asd',
    'アスペルガー',
    'アスペルガー症候群',
    '発達障害',
    '発達障がい',
    'ディスレクシア',
    '失読症',
    '読字障害',
    'dyslexia',
    '学習障害',
    '学習障がい',
    'ディスカリキュリア',
    '算数障害',
    '精神疾患',
    '精神障害',
    '身体障害',
    '身体障がい',
  ],
  personReferences: [
    '私',
    'わたし',
    'あなた',
    '彼',
    '彼女',
    '学習者',
    '生徒',
    '児童',
    '学生',
    '子ども',
    '子供',
    'ユーザー',
    'プロフィール',
  ],
  possessiveDeterminers: [],
  attributionPhrases: [],
  inferenceMarkers: [
    'かもしれない',
    'おそらく',
    'たぶん',
    '疑い',
    '傾向',
    'ようだ',
    'と思われる',
  ],
  determiners: [],
  // No letter case — the Latin "capitalized token = person name" heuristic is
  // inapplicable and is NOT used. Named attribution is detected structurally
  // instead, via the topic/possessive particles and honorific suffixes below.
  scriptHasCase: false,
  // `PERSON` expands to the personReferences alternation, `LEX` to the full
  // lexeme alternation. The subject is deliberately restricted to a person
  // reference or an honorific-marked name — an earlier draft accepted ANY
  // preceding CJK token before は/の, which false-fired on ordinary
  // educational prose ("この章では…失読症…" — "in this chapter … dyslexia").
  rawAttributionPatterns: [
    // "<person reference>は/の/には … <lexeme>" within one clause.
    String.raw`PERSON(?:は|の|には)[^。！？\n]{0,24}?LEX`,
    // "<name>さん/くん/ちゃん(は|の) … <lexeme>" — the honorific marks a person,
    // in either script (Japanese or a Latin-script name in mixed prose).
    String.raw`[\p{Script=Han}\p{Script=Katakana}\p{Script=Hiragana}\p{L}]{1,12}(?:さん|くん|ちゃん|君)(?:は|の|には)?[^。！？\n]{0,24}?LEX`,
  ],
};

const NB: LanguageCorpus = {
  language: 'nb',
  confidence: 'model-generated',
  lexemes: [
    'adhd',
    // NOTE: Norwegian "ADD" deliberately OMITTED — homograph of English "add".
    'autisme',
    'autistisk',
    'autist',
    'autismespekterforstyrrelse',
    'dysleksi',
    'dyslektiker',
    'dyslektisk',
    'ordblind',
    'ordblindhet',
    'dyskalkuli',
    'lærevansker',
    'lærevanske',
    'lese- og skrivevansker',
    'psykisk lidelse',
    'psykisk sykdom',
    'fysisk funksjonsnedsettelse',
    'funksjonsnedsettelse',
  ],
  personReferences: [
    'jeg',
    'du',
    'han',
    'hun',
    'de',
    'eleven',
    'elev',
    'student',
    'barnet',
    'barn',
    'bruker',
    'brukeren',
    'profil',
  ],
  possessiveDeterminers: [
    'hans',
    'hennes',
    'deres',
    'min',
    'mitt',
    'din',
    'ditt',
    'elevens',
    'barnets',
    'brukerens',
  ],
  attributionPhrases: [
    'har',
    'hadde',
    'er',
    'var',
    'ble diagnostisert med',
    'har fått diagnosen',
    'viser tegn på',
    'kan ha',
    'har sannsynligvis',
    'har muligens',
  ],
  inferenceMarkers: [
    'kan',
    'sannsynligvis',
    'muligens',
    'kanskje',
    'ser ut',
    'tegn på',
    'mistanke',
  ],
  determiners: ['en', 'ei', 'et', 'den', 'det'],
  scriptHasCase: true,
};

export const LANGUAGE_CORPORA: Readonly<
  Record<ConversationLanguage, LanguageCorpus>
> = {
  en: EN,
  cs: CS,
  es: ES,
  fr: FR,
  de: DE,
  it: IT,
  pt: PT,
  pl: PL,
  ja: JA,
  nb: NB,
};

export const CORPUS_LANGUAGES = Object.keys(
  LANGUAGE_CORPORA,
) as readonly ConversationLanguage[];
