import {
  classifyPersistedLearningText,
  type PersistedTextDisposition,
} from './persisted-remediation';
import type { LearningTextFieldKind } from './scan';

/**
 * [WI-2753 rework] Classify rows that carry MANY free-text values each.
 *
 * The four scalar surfaces have one text per row, so `PersistedTextRow`'s
 * `{ id, text }` was enough. The surfaces this rework adds do not: a
 * `learning_profiles` row holds six JSONB arrays of entries, and a
 * `memory_facts` row carries the same sentence in `text` and again inside
 * `metadata`. Both need a verdict per VALUE, then a decision per ROW.
 *
 * The classifier is already text-granular — it keys everything on an opaque
 * `id` — so this does not widen it. It addresses each value by a composite id
 * and regroups the verdicts afterwards. Keeping one classification path is the
 * point: AC-3 requires the gate be the sole classifier, and a second entry
 * point is how a surface drifts into its own vocabulary.
 *
 * A `path` is caller-defined and opaque here (`interests.3.label`,
 * `metadata.subject`). It is never logged with the text and never persisted; it
 * exists so the caller can put the verdict back where the value came from.
 */
export interface FieldText {
  /** Identifies the value within its row. Opaque to this module. */
  readonly path: string;
  readonly text: string | null | undefined;
}

export interface MultiTextRow {
  readonly id: string;
  readonly fields: readonly FieldText[];
}

export interface FieldVerdict {
  readonly path: string;
  readonly disposition: PersistedTextDisposition;
}

export interface RowFieldVerdicts {
  readonly id: string;
  /** Only the paths whose value must be destroyed. */
  readonly remediate: readonly string[];
  /** Paths left untouched for a human — ambiguous, never resolved by deletion. */
  readonly review: readonly string[];
  readonly all: readonly FieldVerdict[];
}

/**
 * `#` cannot appear in a row id (they are UUIDs) and the path is generated by
 * this codebase, so the join is unambiguous in both directions.
 */
const SEPARATOR = '#';

function compositeId(rowId: string, path: string): string {
  return `${rowId}${SEPARATOR}${path}`;
}

function splitCompositeId(composite: string): {
  rowId: string;
  path: string;
} {
  const at = composite.indexOf(SEPARATOR);
  return {
    rowId: composite.slice(0, at),
    path: composite.slice(at + SEPARATOR.length),
  };
}

/**
 * Classify every field of every row in ONE batched pass, and return the
 * verdicts grouped by row.
 *
 * Batching matters beyond speed: the classifier scans each text under all ten
 * attribution grammars, so a per-field call would multiply the grammar passes
 * by the number of fields on the row for no additional coverage.
 */
export async function classifyRowFields(input: {
  readonly fieldKind: LearningTextFieldKind;
  readonly rows: readonly MultiTextRow[];
}): Promise<RowFieldVerdicts[]> {
  const verdicts = await classifyPersistedLearningText({
    fieldKind: input.fieldKind,
    rows: input.rows.flatMap((row) =>
      row.fields.map((field) => ({
        id: compositeId(row.id, field.path),
        text: field.text,
      })),
    ),
  });

  const byRow = new Map<string, FieldVerdict[]>(
    input.rows.map((row) => [row.id, []]),
  );
  for (const verdict of verdicts) {
    const { rowId, path } = splitCompositeId(verdict.id);
    byRow.get(rowId)?.push({ path, disposition: verdict.disposition });
  }

  return input.rows.map((row) => {
    const all = byRow.get(row.id) ?? [];
    return {
      id: row.id,
      all,
      remediate: all
        .filter((field) => field.disposition === 'remediate')
        .map((field) => field.path),
      review: all
        .filter((field) => field.disposition === 'review')
        .map((field) => field.path),
    };
  });
}

/**
 * [WI-2753] Applies the remediation classification to persisted rows.
 *
 * SCRUB-IN-PLACE, NOT DELETE. AC-2 inherits the scalar-evidence-identity
 * precedent that a purge preserves the record: the row and its relationships
 * survive, only the offending text goes. Two of the four columns here are
 * NOT NULL `text`, which does NOT force a migration — "scrub" on a text column
 * means overwriting with a redaction placeholder, not setting null. That
 * distinction is what keeps this item free of any schema change.
 */
export const REDACTED_PLACEHOLDER = '[redacted: clinical inference removed]';

export interface SurfaceRemediationReport {
  readonly surface: string;
  /** Rows carrying text that was classified. */
  readonly scanned: number;
  /** Rows whose text was an attribution and was scrubbed. */
  readonly remediated: number;
  /**
   * Rows the gate blocked as `unclear` — reported, never modified. These are
   * the ambiguous cases (an educational reference reads the same as a clinical
   * one under migration provenance), and resolving ambiguity by destroying
   * learner-visible text is not something an unattended backfill may do.
   */
  readonly review: number;
  /**
   * Rows classified `remediate` whose bytes changed between the scan and the
   * write, so the guarded update matched nothing and the row was left alone.
   * A later run reclassifies whatever is there now; reporting the count keeps
   * that visible instead of letting `remediated` silently under-count.
   */
  readonly skippedChanged: number;
}
