-- @freeze-only
-- =============================================================================
-- M-SUBSCRIPTIONS-DROP — drop the retained legacy `subscriptions` table + its
-- 2 orphaned enum types. WI-805 (CUT-B billing fast-follow), the coupled
-- billing-subsystem slice carved out of WI-586's M-DROP (0118).
--
-- [WI-586 drop-4 reshape] 0118 (M-DROP) dropped 4 identity tables but RETAINED
-- `subscriptions` and KEPT the subscription_status / subscription_tier enums,
-- because `subscriptions` still used them. This migration is the deferred 5th
-- drop: now that the billing readers serve v2 under flag-on (WI-586 sweep +
-- WI-810 quota-reset cron) and the flip has soaked, the legacy `subscriptions`
-- table and its 2 enums are removed.
--
-- FK-REHOME PRECONDITION — ALREADY SATISFIED BY 0117 (M-REPOINT), NOT REDONE
-- HERE. 0117's repoint loop (target_map `subscriptions -> subscription`)
-- repointed the subscription_id FK of all 4 quota children
-- (quota_pools, profile_quota_usage, top_up_credits, usage_events) onto the v2
-- `subscription` table, AND repointed `subscriptions.account_id -> organization`.
-- 0117 then asserts (post-state completeness check) that NO live table still
-- holds an FK to a legacy parent. Consequence: by the time this file runs,
-- `subscriptions` has ZERO inbound FK dependents, so the plain DROP TABLE below
-- (no CASCADE) succeeds. If 0117 did NOT run, an un-repointed satellite FK still
-- targets `subscriptions` and Postgres BLOCKS the drop loud on the dangling
-- dependency — intentional: no CASCADE, so an incomplete repoint refuses to drop
-- rather than silently cascading.
--
-- (The 4 satellites' Drizzle schema in packages/database/src/schema/billing.ts
-- still shows `.references(() => subscriptions.id)` — schema realignment to v2
-- `subscription` is deferred to WI-779 legacy-symbol removal, mirroring how 0117
-- / 0118 left billing.ts's accounts/profiles references intact. The DB FK is the
-- source of truth here; the schema lag is the committed freeze-only pattern.)
--
-- STATUS: FREEZE-ONLY DRAFT — NOT AUTO-APPLIED. Lives in
-- apps/api/drizzle/_freeze-only/ and is deliberately NOT registered in
-- meta/_journal.json, so drizzle-kit migrate never sees it and it cannot
-- auto-apply on a deploy (the `-- @freeze-only` marker on line 1 records this).
-- It is promoted to the next free migration number and applied by the operator
-- AFTER 0117 + 0118 have landed and the flip has soaked — operator-delegated,
-- like #11 (0118), with a fresh pre-drop Neon snapshot taken first.
--
-- ## Rollback
-- IMPOSSIBLE in place. Once `subscriptions` drops, the legacy billing rows are
-- gone. Recovery is ONLY a Neon PITR rewind of the whole branch to the fresh
-- pre-drop marker the operator takes immediately before applying this file. Do
-- NOT apply until the operator has taken that snapshot and cleared the WI-805
-- drop gate. IF EXISTS is present only so a rehearsal re-run is a clean no-op —
-- it is NOT a substitute for the PITR marker.
-- =============================================================================

DROP TABLE IF EXISTS subscriptions;

DROP TYPE IF EXISTS subscription_status, subscription_tier;
