import { matrixFixtures } from './__fixtures__/navigation-matrix';
import {
  resolveNavigationContract,
  type RouteParams,
} from './navigation-contract';

// ---------------------------------------------------------------------------
// Per-row explicit structural assertions (replaces toMatchSnapshot).
//
// Each row of the matrix fixture is fully checked with toEqual so that:
//   - contract diffs are readable (field-level, not file-level)
//   - reviewers can verify the expected values without running jest --updateSnapshot
//   - CI failures show exactly which field changed
//
// Expected values recovered from the committed snapshot at:
//   apps/mobile/src/lib/__snapshots__/navigation-contract.snapshot.test.ts.snap
// ---------------------------------------------------------------------------

const LINKED_CHILD_ID = '00000000-0000-7000-a000-000000000201';

describe('navigation-contract matrix snapshot', () => {
  matrixFixtures.forEach((fixture) => {
    it(`${fixture.id}: ${fixture.label}`, () => {
      const contract = resolveNavigationContract(fixture.context);

      const probeKey = (
        route: string,
        params: RouteParams | undefined,
      ): string => (params ? `${route}:${JSON.stringify(params)}` : route);

      const resolved = {
        shape: contract.shape,
        effectiveAppContext: contract.effectiveAppContext,
        isFamilyCapable: contract.isFamilyCapable,
        isParentProxy: contract.isParentProxy,
        visibleTabs: [...contract.visibleTabs].sort(),
        home: contract.home,
        chrome: contract.chrome,
        gates: contract.gates,
        queryScope: contract.queryScope,
        diagnostic: {
          ...contract.diagnostic,
          linkedChildIds: [...contract.diagnostic.linkedChildIds].sort(),
        },
        canEnter: Object.fromEntries(
          fixture.probeRoutes.map((p) => [
            probeKey(p.route, p.params),
            contract.canEnter(p.route, p.params),
          ]),
        ),
        isSurfaced: Object.fromEntries(
          fixture.probeRoutes.map((p) => [
            probeKey(p.route, p.params),
            contract.isSurfaced(p.route, p.params),
          ]),
        ),
      };

      if (fixture.id === 'row-1') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000101',
            effectiveAppContext: 'study',
            isFamilyCapable: false,
            isParentProxy: false,
            linkedChildIds: [],
            reason: 'explicit-study',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: false,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: false,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: false,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000101',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-2') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000101',
            effectiveAppContext: 'study',
            isFamilyCapable: false,
            isParentProxy: false,
            linkedChildIds: [],
            reason: 'family-intent-without-family-links',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: false,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: false,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: false,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000101',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-3') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'global-header',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000102',
            effectiveAppContext: 'study',
            isFamilyCapable: true,
            isParentProxy: false,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'explicit-study',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: false,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: false,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: true,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: true,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000102',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-4') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            home: true,
            library: false,
            'more/account': true,
            progress: true,
            'progress/saved': false,
            recaps: true,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': true,
          },
          chrome: {
            modeSwitcher: 'global-header',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000102',
            effectiveAppContext: 'family',
            isFamilyCapable: true,
            isParentProxy: false,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'explicit-family',
            role: 'owner',
            shape: 'family',
          },
          effectiveAppContext: 'family',
          gates: {
            progressScope: 'children',
            sessionIsOwner: true,
            showAccommodationChildEditor: true,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: true,
            showExportDelete: true,
            showFamilyChildActivity: true,
            showFamilyHome: true,
            showInlineStudyInvite: true,
            showLearnThisToo: true,
            showLearningActions: true,
            showProgressProfilePicker: true,
            showRemoveFamilyMember: true,
          },
          home: {
            iconName: 'Users',
            screen: 'FamilyHome',
            titleKey: 'tabs.children',
          },
          isFamilyCapable: true,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            home: true,
            library: false,
            'more/account': true,
            progress: true,
            'progress/saved': false,
            recaps: true,
            session: false,
            subscription: true,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'family',
            profileId: '00000000-0000-7000-a000-000000000102',
          },
          shape: 'family',
          visibleTabs: ['home', 'more', 'progress', 'recaps'],
        });
      } else if (fixture.id === 'row-5') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            home: true,
            library: false,
            'more/account': true,
            progress: true,
            'progress/saved': false,
            recaps: true,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': true,
          },
          chrome: {
            modeSwitcher: 'global-header',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000102',
            effectiveAppContext: 'family',
            isFamilyCapable: true,
            isParentProxy: false,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'profile-default-family',
            role: 'owner',
            shape: 'family',
          },
          effectiveAppContext: 'family',
          gates: {
            progressScope: 'children',
            sessionIsOwner: true,
            showAccommodationChildEditor: true,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: true,
            showExportDelete: true,
            showFamilyChildActivity: true,
            showFamilyHome: true,
            showInlineStudyInvite: true,
            showLearnThisToo: true,
            showLearningActions: true,
            showProgressProfilePicker: true,
            showRemoveFamilyMember: true,
          },
          home: {
            iconName: 'Users',
            screen: 'FamilyHome',
            titleKey: 'tabs.children',
          },
          isFamilyCapable: true,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: true,
            home: true,
            library: false,
            'more/account': true,
            progress: true,
            'progress/saved': false,
            recaps: true,
            session: false,
            subscription: true,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'family',
            profileId: '00000000-0000-7000-a000-000000000102',
          },
          shape: 'family',
          visibleTabs: ['home', 'more', 'progress', 'recaps'],
        });
      } else if (fixture.id === 'row-6') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'global-header',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000104',
            effectiveAppContext: 'study',
            isFamilyCapable: true,
            isParentProxy: false,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'explicit-study',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: false,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: false,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: true,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: true,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000104',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-7') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': false,
            progress: true,
            'progress/saved': false,
            recaps: false,
            session: false,
            subscription: false,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'required',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000102',
            effectiveAppContext: 'study',
            isFamilyCapable: true,
            isParentProxy: true,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'parent-proxy',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: false,
            showAccommodationChildEditor: false,
            showAccountSecurity: false,
            showAddChild: false,
            showBilling: false,
            showCelebrationsChildEditor: false,
            showExportDelete: false,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: false,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: true,
          isParentProxy: true,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': false,
            progress: true,
            'progress/saved': false,
            recaps: false,
            session: false,
            subscription: false,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000102',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'progress'],
        });
      } else if (fixture.id === 'row-8') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: false,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: LINKED_CHILD_ID,
            effectiveAppContext: 'study',
            isFamilyCapable: false,
            isParentProxy: false,
            linkedChildIds: [],
            reason: 'child-study-only',
            role: 'child',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: false,
            showAccommodationChildEditor: false,
            showAccountSecurity: false,
            showAddChild: false,
            showBilling: false,
            showCelebrationsChildEditor: false,
            showExportDelete: false,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: false,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: false,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: LINKED_CHILD_ID,
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-9') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000202',
            effectiveAppContext: 'study',
            isFamilyCapable: false,
            isParentProxy: false,
            linkedChildIds: [],
            reason: 'explicit-study',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: false,
            showAccountSecurity: true,
            showAddChild: false,
            showBilling: true,
            showCelebrationsChildEditor: false,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: false,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000202',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-10') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: false,
            'more/account': false,
            progress: false,
            'progress/saved': false,
            recaps: false,
            session: false,
            subscription: false,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: null,
            effectiveAppContext: 'study',
            isFamilyCapable: false,
            isParentProxy: false,
            linkedChildIds: [],
            reason: 'profile-loading',
            role: null,
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: false,
            showAccommodationChildEditor: false,
            showAccountSecurity: false,
            showAddChild: false,
            showBilling: false,
            showCelebrationsChildEditor: false,
            showExportDelete: false,
            showFamilyChildActivity: false,
            showFamilyHome: false,
            showInlineStudyInvite: false,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: false,
          },
          home: {
            iconName: 'School',
            screen: 'LearnerHome',
            titleKey: 'tabs.myLearning',
          },
          isFamilyCapable: false,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: false,
            'more/account': false,
            progress: false,
            'progress/saved': false,
            recaps: false,
            session: false,
            subscription: false,
            'topic/relearn': false,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: null,
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'progress'],
        });
      } else if (fixture.id === 'row-v0-flags-off') {
        expect(resolved).toEqual({
          canEnter: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          chrome: {
            modeSwitcher: 'hidden',
            proxyBanner: 'hidden',
          },
          diagnostic: {
            activeProfileId: '00000000-0000-7000-a000-000000000105',
            effectiveAppContext: 'study',
            isFamilyCapable: true,
            isParentProxy: false,
            linkedChildIds: [LINKED_CHILD_ID],
            reason: 'legacy-v0-flags-off',
            role: 'owner',
            shape: 'study',
          },
          effectiveAppContext: 'study',
          gates: {
            progressScope: 'self',
            sessionIsOwner: true,
            showAccommodationChildEditor: true,
            showAccountSecurity: true,
            showAddChild: true,
            showBilling: true,
            showCelebrationsChildEditor: true,
            showExportDelete: true,
            showFamilyChildActivity: false,
            showFamilyHome: true,
            showInlineStudyInvite: true,
            showLearnThisToo: false,
            showLearningActions: true,
            showProgressProfilePicker: false,
            showRemoveFamilyMember: true,
          },
          home: {
            iconName: 'Users',
            screen: 'FamilyHome',
            titleKey: 'tabs.children',
          },
          isFamilyCapable: true,
          isParentProxy: false,
          isSurfaced: {
            [`child/[profileId]/curriculum:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            [`child/[profileId]:{"profileId":"${LINKED_CHILD_ID}"}`]: false,
            home: true,
            library: true,
            'more/account': true,
            progress: true,
            'progress/saved': true,
            recaps: false,
            session: true,
            subscription: true,
            'topic/relearn': true,
            'topic/relearn:{"for":"child"}': false,
          },
          queryScope: {
            appContext: 'study',
            profileId: '00000000-0000-7000-a000-000000000105',
          },
          shape: 'study',
          visibleTabs: ['home', 'library', 'more', 'own-learning', 'progress'],
        });
      } else {
        // Safety net: a new fixture was added to matrixFixtures without a
        // corresponding explicit assertion here. Fail loudly so the developer
        // knows they need to add an assertion block above.
        throw new Error(
          `No explicit assertion found for matrix fixture id="${fixture.id}". ` +
            `Add an else-if block above with the expected values for this row.`,
        );
      }
    });
  });
});
