// WI-3010 — forward-looking guard: husky hook files stay committed 100755.
//
// WHAT THIS IS NOT: it is not fixing a live breakage. Under husky 9 dispatch
// the executable bit on `.husky/<hook>` is INERT. `core.hooksPath` points at
// `.husky/_`, and git execs only the generated shims in there (husky writes
// them 0755 on `prepare`). Each shim sources `.husky/_/h`, which runs the real
// hook by passing its PATH AS AN ARGUMENT TO `sh` — it never execs the hook
// file, so its mode is never consulted. `.husky/_` is gitignored and
// regenerated by `pnpm install`, so no fresh clone/worktree exists in which a
// non-executable `.husky/commit-msg` silently no-ops. Verified by executing
// the hooks at mode 664: `git hook run commit-msg` rejected a bad message
// (exit 1) and `git hook run pre-commit` ran lint-staged + sync-skills.
//
// WHY IT IS ARMED ANYWAY: husky prints "They WILL FAIL in v10.0.0" for the
// deprecated `_/husky.sh` path, i.e. the dispatch layer is explicitly slated
// to change. If v10 execs hook files directly, a 100644 hook becomes a real
// silent no-op — the failure mode this guard makes impossible in advance.
// Treat it as insurance against that change, NOT as evidence that today's
// exec bits are load-bearing.
//
// Reads the INDEX, never the filesystem: on Windows checkouts
// (core.fileMode=false) local modes are meaningless, but the committed mode
// is what mac/Linux consumers receive.

import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

const REPO_ROOT = join(__dirname, '..');

/**
 * Clones process.env with every GIT_* key stripped. Prevents an ambient
 * GIT_DIR (exported by husky during pre-push -> nx -> jest) from redirecting
 * this child git at another repo. Same pattern as
 * scripts/husky-main-guard.test.ts's childGitEnv().
 */
function childGitEnv(): NodeJS.ProcessEnv {
  const env: NodeJS.ProcessEnv = { ...process.env };
  for (const key of Object.keys(env)) {
    if (key.startsWith('GIT_')) {
      delete env[key];
    }
  }
  return env;
}

/** Tracked entries under .husky/, as [mode, path] pairs read from the index. */
function stagedHuskyEntries(): Array<{ mode: string; path: string }> {
  const out = execFileSync('git', ['ls-files', '-s', '--', '.husky'], {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    stdio: ['pipe', 'pipe', 'pipe'],
    env: childGitEnv(),
  });
  return out
    .split('\n')
    .filter((line) => line.trim() !== '')
    .map((line) => {
      // `<mode> <sha> <stage>\t<path>`
      const [meta, path] = line.split('\t');
      return { mode: meta.split(' ')[0], path };
    });
}

describe('husky hook modes (WI-3010)', () => {
  it('tracks the hook files we expect (guard cannot pass vacuously)', () => {
    const paths = stagedHuskyEntries().map((e) => e.path);
    // An empty or truncated listing would make the mode assertion below pass
    // trivially, so pin the hooks that must be present.
    expect(paths).toEqual(
      expect.arrayContaining([
        '.husky/commit-msg',
        '.husky/pre-commit',
        '.husky/pre-push',
      ]),
    );
  });

  it('stages every .husky hook file as 100755', () => {
    // Everything tracked at the top level of .husky/ IS a hook — that is
    // husky's layout convention; the only non-hook content is the gitignored
    // `_` shim dir, which never appears in the index.
    const offenders = stagedHuskyEntries().filter((e) => e.mode !== '100755');
    expect(offenders).toEqual([]);
  });
});
