#!/usr/bin/env node

/**
 * Generates local env files from Doppler for local development.
 *
 * This script runs during `pnpm install` but gracefully skips if:
 * - Running in CI environment
 * - Doppler CLI is not installed
 * - Doppler is not configured for this project
 *
 * Generates:
 * - apps/api/.dev.vars      (Wrangler local secrets)
 * - apps/mobile/.env.local  (Expo local env)
 *
 * Developers can also run manually: pnpm env:sync
 */

const { execSync, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const DOPPLER_CONFIG = 'dev';
const STALENESS_DAYS = 7;

const OUTPUT_FILES = [
  {
    path: path.join(__dirname, '..', 'apps', 'api', '.dev.vars'),
    description: 'Wrangler local secrets (apps/api/.dev.vars)',
  },
  {
    path: path.join(__dirname, '..', 'apps', 'mobile', '.env.local'),
    description: 'Expo local env (apps/mobile/.env.local)',
  },
];

const CI_ENV_VARS = [
  'CI',
  'GITHUB_ACTIONS',
  'VERCEL',
  'NETLIFY',
  'CIRCLECI',
  'TRAVIS',
  'GITLAB_CI',
  'JENKINS_URL',
];

function isCI() {
  return CI_ENV_VARS.some(
    (v) => process.env[v] === 'true' || process.env[v] === '1' || (v !== 'CI' && process.env[v] !== undefined)
  );
}

function isDopplerInstalled() {
  const result = spawnSync('doppler', ['--version'], { stdio: 'pipe', shell: true });
  return result.status === 0;
}

function isDopplerConfigured() {
  const result = spawnSync('doppler', ['configure', 'get', 'project', '--plain'], {
    stdio: 'pipe',
    shell: true,
  });
  return result.status === 0 && result.stdout.toString().trim() !== '';
}

function downloadSecrets(config) {
  try {
    return execSync(`doppler secrets download --config ${config} --no-file --format env`, {
      encoding: 'utf-8',
      shell: true,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
  } catch {
    return null;
  }
}

function checkStaleness(filePath) {
  try {
    const stats = fs.statSync(filePath);
    const ageInDays = (Date.now() - stats.mtimeMs) / (1000 * 60 * 60 * 24);
    return ageInDays > STALENESS_DAYS;
  } catch {
    return false;
  }
}

function main() {
  console.log('\n\x1b[36m\x1b[1m[Doppler]\x1b[0m Setting up local environment...\n');

  if (isCI()) {
    console.log('\x1b[33m[Doppler]\x1b[0m Skipping env generation (CI environment)\n');
    process.exit(0);
  }

  if (!isDopplerInstalled()) {
    console.log('\x1b[33m[Doppler]\x1b[0m Doppler CLI not installed.\n');
    console.log('   To set up Doppler for local development:');
    console.log('   1. Install CLI: https://docs.doppler.com/docs/install-cli');
    console.log('   2. Run: doppler login');
    console.log('   3. Run: doppler setup  (select project: mentomate, config: dev)');
    console.log('   4. Run: pnpm env:sync\n');
    process.exit(0);
  }

  if (!isDopplerConfigured()) {
    console.log('\x1b[33m[Doppler]\x1b[0m Doppler not configured for this project.\n');
    console.log('   Run: doppler setup  (select project: mentomate, config: dev)');
    console.log('   Then: pnpm env:sync\n');
    process.exit(0);
  }

  // Check staleness of first output file
  const primaryFile = OUTPUT_FILES[0].path;
  if (fs.existsSync(primaryFile) && checkStaleness(primaryFile)) {
    console.log(`\x1b[33m[Doppler]\x1b[0m Env files are over ${STALENESS_DAYS} days old — regenerating...\n`);
  }

  const content = downloadSecrets(DOPPLER_CONFIG);
  if (!content) {
    console.log('\x1b[31m[Doppler]\x1b[0m Failed to download secrets from Doppler');
    console.log('   Check your Doppler configuration and try: pnpm env:sync\n');
    process.exit(0);
  }

  const header = `# Generated by Doppler (config: ${DOPPLER_CONFIG})
# Do not edit manually — run 'pnpm env:sync' to regenerate
# Generated at: ${new Date().toISOString()}
`;

  for (const output of OUTPUT_FILES) {
    const dir = path.dirname(output.path);
    if (!fs.existsSync(dir)) {
      console.log(`\x1b[33m[Doppler]\x1b[0m Skipping ${output.description} (directory not found)`);
      continue;
    }
    fs.writeFileSync(output.path, header + '\n' + content);
    console.log(`\x1b[32m[Doppler]\x1b[0m Generated ${output.description}`);
  }

  console.log('\n   \x1b[90mTo regenerate after secret changes:\x1b[0m pnpm env:sync\n');
}

main();
