import { sql } from 'drizzle-orm';
import type { Database } from './client.js';

// UUID v4/v7 pattern — profileId is always a UUID generated by the app.
// We validate before inlining because SET LOCAL does not accept bound
// parameters ($1 placeholders); the value must be embedded as a literal.
// Validation prevents accidental injection if a non-UUID string is passed.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Execute a callback inside a real Postgres transaction with
 * `app.current_profile_id` set via `SET LOCAL`. This is the
 * foundation for Row-Level Security: RLS policies can reference
 * `current_setting('app.current_profile_id')` to enforce
 * tenant isolation at the database level.
 *
 * The SET LOCAL value is scoped to the transaction — it is
 * automatically cleared on commit or rollback and never leaks
 * to other requests.
 *
 * @throws {Error} if profileId is not a valid UUID (prevents SQL injection
 *   via the raw literal inlining required by SET LOCAL).
 */
export async function withProfileScope<T>(
  db: Database,
  profileId: string,
  fn: (tx: Database) => Promise<T>
): Promise<T> {
  if (!UUID_RE.test(profileId)) {
    throw new Error(
      `withProfileScope: profileId must be a UUID, got: ${JSON.stringify(
        profileId
      )}`
    );
  }
  return db.transaction(async (tx) => {
    // SET LOCAL does not accept parameterized values ($1). The profileId is
    // validated as a UUID above so inlining it here is safe.
    await tx.execute(
      sql.raw(`SET LOCAL app.current_profile_id = '${profileId}'`)
    );
    return fn(tx as unknown as Database);
  });
}
