import { sql } from 'drizzle-orm';
import type { Database } from './client.js';

// UUID v4/v7 pattern — profileId is always a UUID generated by the app.
// We validate as a defense-in-depth guard before passing to set_config().
// Validation rejects obviously-wrong values early and is locked by rls.test.ts.
const UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * Execute a callback inside a real Postgres transaction with
 * `app.current_profile_id` set via `SET LOCAL`. This is the
 * foundation for Row-Level Security: RLS policies can reference
 * `current_setting('app.current_profile_id')` to enforce
 * tenant isolation at the database level.
 *
 * The SET LOCAL value is scoped to the transaction — it is
 * automatically cleared on commit or rollback and never leaks
 * to other requests.
 *
 * ## Nested transactions / savepoint semantics (CR-2026-05-21-164, BUG-569)
 *
 * The `fn` callback receives the Drizzle transaction handle typed as
 * `Database` (via `tx as unknown as Database`). This means callers CAN call
 * `tx.transaction(...)` inside `fn`. Drizzle detects the nesting and silently
 * opens a **SAVEPOINT** instead of a new `BEGIN`. Consequently:
 *
 * - Rolling back the inner `.transaction()` only rolls back to the savepoint;
 *   the outer transaction (and the `SET LOCAL` GUC) remains active and will
 *   commit normally unless the outer call also throws.
 * - This is intentional behaviour inherited from Drizzle's nested-transaction
 *   model — it is NOT a bug in `withProfileScope` itself.
 * - Callers that need true transactional independence (e.g. separate
 *   COMMIT/ROLLBACK) must open a second database connection rather than
 *   nesting inside `withProfileScope`.
 *
 * The savepoint behaviour is locked down by the `[BUG-569]` test block in
 * `rls.test.ts`. Any future refactor that changes this semantics (e.g.
 * introducing a branded `ScopedTx` type that removes `.transaction()`) must
 * update those tests and this comment.
 *
 * @throws {Error} if profileId is not a valid UUID (defense-in-depth guard).
 */
export async function withProfileScope<T>(
  db: Database,
  profileId: string,
  fn: (tx: Database) => Promise<T>,
): Promise<T> {
  if (!UUID_RE.test(profileId)) {
    throw new Error(
      `withProfileScope: profileId must be a UUID, got: ${JSON.stringify(
        profileId,
      )}`,
    );
  }
  return db.transaction(async (tx) => {
    // set_config(setting, value, is_local) accepts a bound parameter for
    // the value ($1), unlike SET LOCAL which requires literal inlining.
    // is_local=true scopes the setting to the current transaction.
    await tx.execute(
      sql`SELECT set_config('app.current_profile_id', ${profileId}, true)`,
    );
    return fn(tx as unknown as Database);
  });
}
